### ISSUE TITLE
Having issues with php74 of remi repo

### ISSUE THREAD

**Issue by devindya18** [oracle/centos2ol#122]
I have already disabled the remi repo but still getting the following error

Please advise 

Complete!
Last metadata expiration check: 0:00:48 ago on Wed 05 Jan 2022 07:08:42 AM EST.
> Leaving Shell
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Updating initrd...
Switch successful. Syncing with Oracle Linux repositories.
Oracle Linux 8 EPEL Packages for Development (x86_64)                                                                       49 MB/s |  26 MB     00:00    
Last metadata expiration check: 0:00:05 ago on Wed 05 Jan 2022 07:10:00 AM EST.
Error: 
 Problem: package php74-php-pecl-ssh2-1.3.1-1.el8.remi.x86_64 requires libssh2(x86-64) >= 1.9.0, but none of the providers can be installed
  - libssh2-1.9.0-5.el8.x86_64 does not belong to a distupgrade repository
  - problem with installed package php74-php-pecl-ssh2-1.3.1-1.el8.remi.x86_64
  - package libssh2-1.9.0-5.el8.x86_64 is filtered out by modular filtering
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Could not automatically sync with Oracle Linux repositories.
Check the output of 'yum distro-sync' to manually resolve the issue.
For assistance, please open an issue via GitHub: https://github.com/oracle/centos2ol/.

Is there a way to disable the package ?

Thank you

**Comment by devindya18** [comment]
and getting this error on another web server 

Total                                                                                                                      6.2 MB/s | 499 MB     01:20     
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: Transaction test error:
  file /usr/share/pixmaps/poweredby.png from install of oracle-logos-httpd-84.5-1.0.1.el8.noarch conflicts with file from package centos-logos-httpd-85.8-1.el8.noarch
  file /usr/share/testpage/index.html from install of oracle-logos-httpd-84.5-1.0.1.el8.noarch conflicts with file from package centos-logos-httpd-85.8-1.el8.noarch

Could not automatically sync with Oracle Linux repositories.
Check the output of 'yum distro-sync' to manually resolve the issue.
For assistance, please open an issue via GitHub: https://github.com/oracle/centos2ol/.

**Comment by devindya18** [comment]
please note that i moved all the repos epel and remi repos to /root/repos. 
I also ran yum clean all ; dnf clean all

**Comment by Djelibeybi** [comment]
You'll have to remove the RPMs as well, I'm afraid. We have our own PHP 7.4 packages, so you could try enabling that repo to reinstall or replace the ones you have.

**Comment by devindya18** [comment]
Thank you for your reply
Is there a way to prevent it from updating this package ?

**Comment by Djelibeybi** [comment]
No, because the Remi packages are not allowing the script to replace the CentOS httpd packages.

**Comment by totalamateurhour** [comment]
Closing this issue. @devindya18 information about our PHP7.4 on Oracle Linux yum server is here: https://yum.oracle.com/oracle-linux-php.html
