### ISSUE TITLE
Script error for Rocky Linux migration

### ISSUE THREAD

**Issue by liefra** [oracle/centos2ol#123]
I'm trying the run the script on a Rocky Linux (rocky-release-8.5-3.el8.noarch) and get the following error

```[root@rocky-16gb-fsn1-1 ~]# sh centos2ol.sh -rkV
Checking for required packages...
Checking your distribution...
Creating a list of RPMs installed before the switch
Verifying RPMs installed before the switch against RPM database
epel-release-8-13.el8.noarch
Checking for yum lock...
Checking for required python packages...
centos2ol.sh: line 205: syntax error near unexpected token <' ```

**Comment by totalamateurhour** [comment]
Can you run the script as follows to see more details about why it fails.

`sudo bash -x centos2ol.sh`

**Comment by liefra** [comment]
I just retied the Rocky Linux migration using the `centos2ol.sh` script. This time everything worked fine without any error. So it seems that my previous error was due to some temporary version mismatches. I don't know what went wrong at that time, but now all worked just fine. 
 
Thanks @totalamateurhour
