### ISSUE TITLE
Is it safe to perform migration with custom kernel modules

### ISSUE THREAD

**Issue by markohrastovec** [oracle/centos2ol#127]
I have a server with kmod-megaraid_sas-07.717.02.00-1.el8_5.elrepo.x86_64 package installed to support RAID and its disk drives. I do not plan to install UEK.

Can I migrate ti Oracle Linux 8 and not lose that support? Looking at the script, I believe it should work.

I do not have a spare server to test migration, but I have some servers running Oracle Linux with kmod-megaraid_sas, so I know it works.

**Comment by Djelibeybi** [comment]
It _might_ work, but I have no way to test it. If you don't select full package reinstall, it should be ok. Worst case it'll either refuse to migrate or you may have to reinstall after migration. The latter suggests it may be worth installing the UEK anyway, at least to give you an alternative boot option, as it has that driver built in. After you've got it working, you can then remove the UEK, if required.

**Comment by markohrastovec** [comment]
Wow! I was not aware that UEK has these drivers built in.

Well, I said no guts no glory, and tried it yesterday. First the script exited, because I had no yum utils. I installed it manually, and then the script did its magic. I am glad to confirm that it works flawlessy with 4.18 kernel. Maybe I will try UEK, too.

Thanks.

**Comment by Djelibeybi** [comment]
The latest stable UEK release is based on mainline 5.4.17 and includes a lot more than the default upstream kernel. It also powers (almost) all of Oracle's Engineered Systems as well as Oracle Cloud, so it's definitely enterprise class and production ready. :)

**Comment by totalamateurhour** [comment]
@markohrastovec were you able to try UEK? Closing this issue for now.

**Comment by markohrastovec** [comment]
@totalamateurhour I tried UEK now. It works. I just enabled UEK with dnf, installed kernel-uek and rebooted.
