### ISSUE TITLE
script centos2ol.sh failed to install uek kernel 

### ISSUE THREAD

**Issue by jtome7** [oracle/centos2ol#129]
The conversion script centos2ol.sh worked perfectly on one of my servers; however, on another server, the script failed to install the uek kernel at all.  Can I copy the uek kernel from the first server where the conversion worked, and then, use grubby to make that copied over uek kernel the default on the second server?   I don't recall any error message at the end of the script.   Thanks!

**Comment by scoter-oracle** [comment]
If the second server booted up with the RHCK (Red Hat Compatible Kernel) you can then install the kernel with "yum" or "dnf" by pointing to proper Oracle Linux yum channels.
Do you have a log of the upgrade where UEK hadn't been installed ?

**Comment by jtome7** [comment]
GOOD NEWS! 
It seemed as if 90% of the conversion script had completed OK, so I took a chance on completing the installation of the UEK kernel by running these steps and it worked great!

# dnf install oraclelinux-release-el8
--OR-- upgrade existing package:
# dnf upgrade oraclelinux-release-el8

Verify UEKR6 kernel repo is "enabled"

# dnf repolist all

ol8_UEKR6   ....................  enabled

Enable UEKR6 kernel repo:

# dnf config-manager --enable ol8_UEKR6

Install the ORACLE UEK KERNEL:

# dnf install kernel-uek

And additionally, install the devel package:

# dnf install kernel-uek-devel

Finally, reboot the system to load the new UEK kernel

# init 6

[jtome@solara ~]$ uname -a
Linux solara 5.4.17-2136.304.4.1.el8uek.x86_64 #2 SMP Tue Feb 8 11:54:24 PST 2022 x86_64 x86_64 x86_64 GNU/Linux


[jtome@solara ~]$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="8.5"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.5"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:5:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.5
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.5
