### ISSUE TITLE
How remove old rescue kernel

### ISSUE THREAD

**Issue by cevin** [oracle/centos2ol#141]
<img width="786" alt="image" src="https://user-images.githubusercontent.com/338110/167358347-78b7e8c0-41ac-470f-aa75-6a8c7a0ee316.png">

`CentOS Linux (4.x ..)`

**Comment by scoter-oracle** [comment]
If you try to update your system you should also get updated RHCK (Red Hat Compatible Kernel) updated on your Oracle Linux installation. If you want to remove the RHCK you can uninstall the same from your OL installation.

**Comment by cevin** [comment]
> If you try to update your system you should also get updated RHCK (Red Hat Compatible Kernel) updated on your Oracle Linux installation. If you want to remove the RHCK you can uninstall the same from your OL installation.

<img width="601" alt="image" src="https://user-images.githubusercontent.com/338110/167392404-0d62a62a-df7f-4884-9d48-3a430dc24b35.png">

But this operation feels dangerous.

Contains packages such as glibc, gcc...

**Comment by cevin** [comment]
> If you try to update your system you should also get updated RHCK (Red Hat Compatible Kernel) updated on your Oracle Linux installation. If you want to remove the RHCK you can uninstall the same from your OL installation.

![image](https://user-images.githubusercontent.com/338110/167393066-65c6ac4f-64cb-4e9d-8610-3a5e7642f3a4.png)

But how do I do it?

In Ubuntu / Debian you just need `apt remove linux-headers-$ver`, but how do you do it in OL or other derivative distributions?

After I remove kernel-headers and reboot, I still see the CentOS kernel in the boot menu.

**Comment by cevin** [comment]
最终使用grubby删除了旧内核

https://docs.oracle.com/en/learn/switch_centos8_linux8/index.html#remove-non-standard-kernels-with-grubby

**Comment by cevin** [comment]
Eventually removed the old kernel using grubby

https://docs.oracle.com/en/learn/switch_centos8_linux8/index.html#remove-non-standard-kernels-with-grubby
