### ISSUE TITLE
An error occurred while attempting to switch this system to Oracle Linux and it may be in an unstable/unbootable state

### ISSUE THREAD

**Issue by sumit120** [oracle/centos2ol#156]
[root@RHEL8_TestVM home]# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.7 (Ootpa)
[root@RHEL8_TestVM home]# rpm -qf /etc/redhat-release
redhat-release-8.7-0.3.el8.x86_64
[root@RHEL8_TestVM home]# uname -r
4.18.0-240.10.1.el8_3.x86_64
[root@RHEL8_TestVM home]# bash centos2ol.sh
Checking for required packages...
Checking your distribution...
package epel-release is not installed
Checking for yum lock...
Checking for required python packages...
Identifying dnf modules that are enabled
Finding your repository directory...
Learning which repositories are enabled...
Repositories enabled before update include:
rhel-8-for-x86_64-baseos-rpms
rhel-8-for-x86_64-appstream-rpms
ol8_baseos_latest
ol8_appstream
ol8_UEKR6
Looking for yumdownloader...
Backing up and removing old repository files...
An error occurred while attempting to switch this system to Oracle Linux and it may be in an unstable/unbootable state. To avoid further issues, the script has terminated.
[root@RHEL8_TestVM home]#

**Comment by Djelibeybi** [comment]
This script doesn't support RHEL, only CentOS.
