### ISSUE TITLE
Error: Package: glibc-devel

### ISSUE THREAD

**Issue by benzpollard** [oracle/centos2ol#161]
Error: Package: glibc-devel-2.17-196.el7_4.2.i686 (PBL_CentOS_7_4_CentOS_Updates_7_4)
           Requires: glibc-headers = 2.17-196.el7_4.2
           Removing: glibc-headers-2.17-196.el7_4.2.x86_64 (@PBL-update/7)
               glibc-headers = 2.17-196.el7_4.2
           Updated By: glibc-headers-2.17-326.0.3.el7_9.x86_64 (ol7_latest)
               glibc-headers = 2.17-326.0.3.el7_9
           Available: glibc-headers-2.17-196.el7.x86_64 (PBL_CentOS_7_4_CentOS_OS_7_4)
               glibc-headers = 2.17-196.el7
           Available: glibc-headers-2.17-222.el7.x86_64 (ol7_latest)
               glibc-headers = 2.17-222.el7
           Available: glibc-headers-2.17-222.0.7.el7.x86_64 (ol7_latest)
               glibc-headers = 2.17-222.0.7.el7
           Available: glibc-headers-2.17-260.0.9.el7.x86_64 (ol7_latest)
               glibc-headers = 2.17-260.0.9.el7
           Available: glibc-headers-2.17-260.0.15.el7_6.3.x86_64 (ol7_latest)
               glibc-headers = 2.17-260.0.15.el7_6.3
           Available: glibc-headers-2.17-260.0.15.el7_6.4.x86_64 (ol7_latest)
               glibc-headers = 2.17-260.0.15.el7_6.4
           Available: glibc-headers-2.17-260.0.15.el7_6.5.x86_64 (ol7_latest)
               glibc-headers = 2.17-260.0.15.el7_6.5
           Available: glibc-headers-2.17-260.0.17.el7_6.5.x86_64 (ol7_latest)
               glibc-headers = 2.17-260.0.17.el7_6.5
           Available: glibc-headers-2.17-260.0.17.el7_6.6.x86_64 (ol7_latest)
               glibc-headers = 2.17-260.0.17.el7_6.6
           Available: glibc-headers-2.17-292.0.1.el7.x86_64 (ol7_latest)
               glibc-headers = 2.17-292.0.1.el7
           Available: glibc-headers-2.17-307.0.1.el7.1.x86_64 (ol7_latest)
               glibc-headers = 2.17-307.0.1.el7.1
           Available: glibc-headers-2.17-317.0.1.el7.x86_64 (ol7_latest)
               glibc-headers = 2.17-317.0.1.el7
           Available: glibc-headers-2.17-322.0.1.el7_9.x86_64 (ol7_latest)
               glibc-headers = 2.17-322.0.1.el7_9
           Available: glibc-headers-2.17-323.0.1.el7_9.x86_64 (ol7_latest)
               glibc-headers = 2.17-323.0.1.el7_9
           Available: glibc-headers-2.17-324.0.1.el7_9.x86_64 (ol7_latest)
               glibc-headers = 2.17-324.0.1.el7_9
           Available: glibc-headers-2.17-325.0.1.el7_9.x86_64 (ol7_latest)
               glibc-headers = 2.17-325.0.1.el7_9
           Available: glibc-headers-2.17-325.0.3.el7_9.x86_64 (ol7_latest)
               glibc-headers = 2.17-325.0.3.el7_9
           Available: glibc-headers-2.17-326.0.1.el7_9.x86_64 (ol7_latest)
               glibc-headers = 2.17-326.0.1.el7_9
Error: Package: glibc-devel-2.17-196.el7_4.2.i686 (PBL_CentOS_7_4_CentOS_Updates_7_4)
           Requires: glibc = 2.17-196.el7_4.2
           Removing: glibc-2.17-196.el7_4.2.i686 (@PBL-update/7)
               glibc = 2.17-196.el7_4.2
           Updated By: glibc-2.17-326.0.3.el7_9.i686 (ol7_latest)
               glibc = 2.17-326.0.3.el7_9
           Available: glibc-2.17-196.el7.i686 (PBL_CentOS_7_4_CentOS_OS_7_4)
               glibc = 2.17-196.el7
           Available: glibc-2.17-222.el7.i686 (ol7_latest)
               glibc = 2.17-222.el7
           Available: glibc-2.17-222.0.7.el7.i686 (ol7_latest)
               glibc = 2.17-222.0.7.el7
           Available: glibc-2.17-260.0.9.el7.i686 (ol7_latest)
               glibc = 2.17-260.0.9.el7
           Available: glibc-2.17-260.0.15.el7_6.3.i686 (ol7_latest)
               glibc = 2.17-260.0.15.el7_6.3
           Available: glibc-2.17-260.0.15.el7_6.4.i686 (ol7_latest)
               glibc = 2.17-260.0.15.el7_6.4
           Available: glibc-2.17-260.0.15.el7_6.5.i686 (ol7_latest)
               glibc = 2.17-260.0.15.el7_6.5
           Available: glibc-2.17-260.0.17.el7_6.5.i686 (ol7_latest)
               glibc = 2.17-260.0.17.el7_6.5
           Available: glibc-2.17-260.0.17.el7_6.6.i686 (ol7_latest)
               glibc = 2.17-260.0.17.el7_6.6
           Available: glibc-2.17-292.0.1.el7.i686 (ol7_latest)
               glibc = 2.17-292.0.1.el7
           Available: glibc-2.17-307.0.1.el7.1.i686 (ol7_latest)
               glibc = 2.17-307.0.1.el7.1
           Available: glibc-2.17-317.0.1.el7.i686 (ol7_latest)
               glibc = 2.17-317.0.1.el7
           Available: glibc-2.17-322.0.1.el7_9.i686 (ol7_latest)
               glibc = 2.17-322.0.1.el7_9
           Available: glibc-2.17-323.0.1.el7_9.i686 (ol7_latest)
               glibc = 2.17-323.0.1.el7_9
           Available: glibc-2.17-324.0.1.el7_9.i686 (ol7_latest)
               glibc = 2.17-324.0.1.el7_9
           Available: glibc-2.17-325.0.1.el7_9.i686 (ol7_latest)
               glibc = 2.17-325.0.1.el7_9
           Available: glibc-2.17-325.0.3.el7_9.i686 (ol7_latest)
               glibc = 2.17-325.0.3.el7_9
           Available: glibc-2.17-326.0.1.el7_9.i686 (ol7_latest)
               glibc = 2.17-326.0.1.el7_9
Error: Package: libstdc++-devel-4.8.5-16.el7_4.2.i686 (PBL_CentOS_7_4_CentOS_Updates_7_4)
           Requires: libstdc++(x86-32) = 4.8.5-16.el7_4.2
           Removing: libstdc++-4.8.5-16.el7_4.2.i686 (@PBL-update/7)
               libstdc++(x86-32) = 4.8.5-16.el7_4.2
           Updated By: libstdc++-4.8.5-44.0.3.el7.i686 (ol7_latest)
               libstdc++(x86-32) = 4.8.5-44.0.3.el7
           Available: libstdc++-4.8.5-16.el7.i686 (PBL_CentOS_7_4_CentOS_OS_7_4)
               libstdc++(x86-32) = 4.8.5-16.el7
           Available: libstdc++-4.8.5-16.el7_4.1.i686 (PBL_CentOS_7_4_CentOS_Updates_7_4)
               libstdc++(x86-32) = 4.8.5-16.el7_4.1
           Available: libstdc++-4.8.5-28.0.1.el7.i686 (ol7_latest)
               libstdc++(x86-32) = 4.8.5-28.0.1.el7
           Available: libstdc++-4.8.5-28.0.1.el7_5.1.i686 (ol7_latest)
               libstdc++(x86-32) = 4.8.5-28.0.1.el7_5.1
           Available: libstdc++-4.8.5-36.0.1.el7.i686 (ol7_latest)
               libstdc++(x86-32) = 4.8.5-36.0.1.el7
           Available: libstdc++-4.8.5-36.0.1.el7_6.1.i686 (ol7_latest)
               libstdc++(x86-32) = 4.8.5-36.0.1.el7_6.1
           Available: libstdc++-4.8.5-36.0.1.el7_6.2.i686 (ol7_latest)
               libstdc++(x86-32) = 4.8.5-36.0.1.el7_6.2
           Available: libstdc++-4.8.5-39.0.1.el7.i686 (ol7_latest)
               libstdc++(x86-32) = 4.8.5-39.0.1.el7
           Available: libstdc++-4.8.5-39.0.3.el7.i686 (ol7_latest)
               libstdc++(x86-32) = 4.8.5-39.0.3.el7
           Available: libstdc++-4.8.5-39.0.5.el7.i686 (ol7_latest)
               libstdc++(x86-32) = 4.8.5-39.0.5.el7
Error: Package: katello-ca-consumer-wg9plitior01.pblipa.ca-1.0-1.noarch (installed)
           Requires: subscription-manager
           Removing: subscription-manager-1.24.26-4.el7.centos.x86_64 (@PBL-update/7)
               subscription-manager = 1.24.26-4.el7.centos
           Obsoleted By: rhn-client-tools-2.0.2-24.0.9.el7.x86_64 (ol7_latest)
               Not found
           Available: subscription-manager-1.19.21-1.el7.centos.x86_64 (PBL_CentOS_7_4_CentOS_OS_7_4)
               subscription-manager = 1.19.21-1.el7.centos
           Available: subscription-manager-1.19.23-1.el7.centos.x86_64 (PBL_CentOS_7_4_CentOS_Updates_7_4)
               subscription-manager = 1.19.23-1.el7.centos
Error: Package: katello-host-tools-3.3.5-4.el7.noarch (PBL_Katello_Client_CentOS_7_Katello_Client_EL7)
           Requires: subscription-manager
           Removing: subscription-manager-1.24.26-4.el7.centos.x86_64 (@PBL-update/7)
               subscription-manager = 1.24.26-4.el7.centos
           Obsoleted By: rhn-client-tools-2.0.2-24.0.9.el7.x86_64 (ol7_latest)
               Not found
           Available: subscription-manager-1.19.21-1.el7.centos.x86_64 (PBL_CentOS_7_4_CentOS_OS_7_4)
               subscription-manager = 1.19.21-1.el7.centos
           Available: subscription-manager-1.19.23-1.el7.centos.x86_64 (PBL_CentOS_7_4_CentOS_Updates_7_4)
               subscription-manager = 1.19.23-1.el7.centos
Error: Package: katello-host-tools-fact-plugin-3.3.5-4.el7.noarch (PBL_Katello_Client_CentOS_7_Katello_Client_EL7)
           Requires: subscription-manager
           Removing: subscription-manager-1.24.26-4.el7.centos.x86_64 (@PBL-update/7)
               subscription-manager = 1.24.26-4.el7.centos
           Obsoleted By: rhn-client-tools-2.0.2-24.0.9.el7.x86_64 (ol7_latest)
               Not found
           Available: subscription-manager-1.19.21-1.el7.centos.x86_64 (PBL_CentOS_7_4_CentOS_OS_7_4)
               subscription-manager = 1.19.21-1.el7.centos
           Available: subscription-manager-1.19.23-1.el7.centos.x86_64 (PBL_CentOS_7_4_CentOS_Updates_7_4)
               subscription-manager = 1.19.23-1.el7.centos
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Uploading Enabled Repositories Report
Loaded plugins: fastestmirror, langpacks, product-id, subscription-manager
+ exit_message 'Could not automatically sync with Oracle Linux repositories.
Check the output of '\''yum distro-sync'\'' to manually resolve the issue.'
+ echo 'Could not automatically sync with Oracle Linux repositories.
Check the output of '\''yum distro-sync'\'' to manually resolve the issue.'
Could not automatically sync with Oracle Linux repositories.
Check the output of 'yum distro-sync' to manually resolve the issue.
+ echo 'For assistance, please open an issue via GitHub: https://github.com/oracle/centos2ol/.'
For assistance, please open an issue via GitHub: https://github.com/oracle/centos2ol/.
+ exit 1

**Comment by totalamateurhour** [comment]
Can you re-run the script with the `-x` flag and share the output?

```
sudo bash -x centos2ol.sh
```

**Comment by benzpollard** [comment]
i use this ....        bash -x centos2ol.sh 2>&1 | tee /root/cenos2ol.$HOSTNAME.log


[results_Centos2ol.txt](https://github.com/oracle/centos2ol/files/11399296/results_Centos2ol.txt)

**Comment by benzpollard** [comment]
I got the solution

I just remove the following
glibc-devel-2.17-196.el7_4.2.i686
libstdc++-devel-4.8.5-16.el7_4.2.i686
katello-ca-consumer-wg9plitior01.pblipa.ca-1.0-1.noarch
katello-host-tools-3.3.5-4.el7.noarch
katello-host-tools-fact-plugin-3.3.5-4.el7.noarch

**Comment by totalamateurhour** [comment]
Glad you solved it.
