### ISSUE TITLE
unable to Switch from CentOS 8 to Oracle Linux 8

### ISSUE THREAD

**Issue by sharans147** [oracle/centos2ol#172]
Hi Team,

We are trying to migrate the server from CentOS Linux release 8.0.1905 (Core) to Oracle Linux 8.0. but getting error while running Centos2ol script.
Kindly check and provide solution to migrate.

Error code: 

+ grep '\.repo$'
++ final_failure
++ echo 'An error occurred while attempting to switch this system to Oracle Linux and it may be in an unstable/unbootable state. To avoid further issues, the script has terminated.'
An error occurred while attempting to switch this system to Oracle Linux and it may be in an unstable/unbootable state. To avoid further issues, the script has terminated.

**Comment by scoter-oracle** [comment]
Hi, can you share the full log of the execution ?

**Comment by sharans147** [comment]
[centos2ol-script.txt](https://github.com/oracle/centos2ol/files/15076122/centos2ol-script.txt)
[CentOS Convertion script error.txt](https://github.com/oracle/centos2ol/files/15076125/CentOS.Convertion.script.error.txt)

**Comment by sharans147** [comment]
Uploaded the script which we have used and error full output

**Comment by sharans147** [comment]
> Hi, can you share the full log of the execution ?

uploaded the logs

**Comment by scoter-oracle** [comment]
Please, execute the following commands on your CentOS 8 machine:

# sudo sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-*
# sudo sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*
# dnf install centos-linux-repos -y

then retry the migration.

**Comment by sharans147** [comment]
Hi Simon Coter,

Already server having below entry in /etc/yum.repos.d/ directory. 

[BaseOS]
name=CentOS-$releasever - Base
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=BaseOS&infra=$infra
#baseurl=http://mirror.centos.org/$contentdir/$releasever/BaseOS/$basearch/os/
baseurl=https://vault.centos.org/8.0.1905/BaseOS/x86_64/os/
#baseurl=http://vault.centos.org
gpgcheck=1
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial

=======================================
[AppStream]
name=CentOS-$releasever - AppStream
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=AppStream&infra=$infra
#baseurl=http://mirror.centos.org/$contentdir/$releasever/AppStream/$basearch/os/
baseurl=http://vault.centos.org/$contentdir/$releasever/AppStream/$basearch/os/
#baseusr=https://vault.centos.org/8.0.1905/AppStream/x86_64/os/
#baseurl=http://vault.centos.org
#baseurl=http://vault.epel.cloud
gpgcheck=1
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial

**Comment by scoter-oracle** [comment]
Ok, so it seems that you're missing the "centos-linux-repos" RPM installed on your system and presumably this is due to the very old release you're running (8.0.1905)

**Comment by sharans147** [comment]
Hi Simon Coter,

Can we try after run the dnf update on the server ?

**Comment by sharans147** [comment]
Hi Team,

We have tried below command and got the below error.

dnf install centos-linux-repos -y



[root@gitlab-app modules.d]# dnf install centos-linux-repos -y
Last metadata expiration check: 0:07:00 ago on Mon 06 May 2024 10:07:08 PM IST.
No match for argument: centos-linux-repos
Error: Unable to find a match: centos-linux-repos

[root@gitlab-app modules.d]# yum update -... by Srinivasalu
Srinivasalu
Yesterday 10:15 PM

[root@gitlab-app modules.d]# yum update --allowerasing
Last metadata expiration check: 0:08:02 ago on Mon 06 May 2024 10:07:08 PM IST.
Error:
Problem 1: problem with installed package qemu-kvm-core-15:2.12.0-64.module_el8.0.0+44+94c1b039.2.x86_64
  - cannot install the best update candidate for package qemu-kvm-core-15:2.12.0-64.module_el8.0.0+44+94c1b039.2.x86_64
  - nothing provides libseccomp >= 2.4.0 needed by qemu-kvm-core-15:4.2.0-59.module_el8.5.0+1002+36725df2.x86_64
  - nothing provides libseccomp >= 2.4.0 needed by qemu-kvm-core-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64
Problem 2: cannot install the best update candidate for package python36-3.6.8-2.module_el8.0.0+33+0a10c0e1.x86_64
  - problem with installed package python36-3.6.8-2.module_el8.0.0+33+0a10c0e1.x86_64
  - nothing provides alternatives >= 1.19.1-1 needed by python36-3.6.8-38.module_el8.5.0+895+a459eca8.x86_64
Problem 3: cannot install the best update candidate for package python3-pip-9.0.3-13.el8.noarch
  - problem with installed package python3-pip-9.0.3-13.el8.noarch
  - nothing provides platform-python-pip = 9.0.3-20.el8 needed by python3-pip-9.0.3-20.el8.noarch
Problem 4: cannot install the best update candidate for package python3-newt-0.52.20-9.el8.x86_64
  - problem with installed package python3-newt-0.52.20-9.el8.x86_64
  - nothing provides newt(x86-64) = 0.52.20-11.el8 needed by python3-newt-0.52.20-11.el8.x86_64
Problem 5: cannot install the best update candidate for package python3-gobject-3.28.3-1.el8.x86_64
  - problem with installed package python3-gobject-3.28.3-1.el8.x86_64
  - nothing provides python3-gobject-base(x86-64) = 3.28.3-2.el8 needed by python3-gobject-3.28.3-2.el8.x86_64
Problem 6: cannot install the best update candidate for package podman-1.0.0-2.git921f98f.module_el8.0.0+58+91b614e7.x86_64
  - problem with installed package podman-1.0.0-2.git921f98f.module_el8.0.0+58+91b614e7.x86_64
  - nothing provides libseccomp >= 2.4.1 needed by podman-3.3.1-9.module_el8.5.0+988+b1f0b741.x86_64
Problem 7: cannot install the best update candidate for package perl-utils-5.26.3-419.el8_4.1.noarch
  - problem with installed package perl-utils-5.26.3-419.el8_4.1.noarch
  - nothing provides perl-libs = 4:5.26.3-420.el8 needed by perl-utils-5.26.3-420.el8.noarch
Problem 8: cannot install the best update candidate for package perl-devel-4:5.26.3-419.el8_4.1.x86_64
  - problem with installed package perl-devel-4:5.26.3-419.el8_4.1.x86_64
  - nothing provides perl-libs(x86-64) = 4:5.26.3-420.el8 needed by perl-devel-4:5.26.3-420.el8.x86_64
Problem 9: cannot install the best update candidate for package perl-4:5.26.3-419.el8_4.1.x86_64
  - problem with installed package perl-4:5.26.3-419.el8_4.1.x86_64
  - nothing provides perl-libs(x86-64) = 4:5.26.3-420.el8 needed by perl-4:5.26.3-420.el8.x86_64
  - nothing provides perl-interpreter(x86-64) = 4:5.26.3-420.el8 needed by perl-4:5.26.3-420.el8.x86_64
Problem 10: cannot install the best update candidate for package lua-5.3.4-10.el8.x86_64
  - problem with installed package lua-5.3.4-10.el8.x86_64
  - nothing provides lua-libs = 5.3.4-12.el8 needed by lua-5.3.4-12.el8.x86_64
Problem 11: cannot install the best update candidate for package gvfs-smb-1.36.2-1.el8.x86_64
  - problem with installed package gvfs-smb-1.36.2-1.el8.x86_64
  - nothing provides libsmbclient.so.0(SMBCLIENT_0.6.0)(64bit) needed by gvfs-smb-1.36.2-11.el8.x86_64
Problem 12: cannot install the best update candidate for package gnome-software-3.30.6-1.el8.x86_64
  - problem with installed package gnome-software-3.30.6-1.el8.x86_64
  - nothing provides libfwupd.so.2(LIBFWUPD_1.2.7)(64bit) needed by gnome-software-3.36.1-10.el8.x86_64
  - nothing provides libfwupd.so.2(LIBFWUPD_1.3.3)(64bit) needed by gnome-software-3.36.1-10.el8.x86_64
  - nothing provides libxmlb.so.1()(64bit) needed by gnome-software-3.36.1-10.el8.x86_64
  - nothing provides libxmlb.so.1(LIBXMLB_0.1.0)(64bit) needed by gnome-software-3.36.1-10.el8.x86_64
  - nothing provides libxmlb.so.1(LIBXMLB_0.1.1)(64bit) needed by gnome-software-3.36.1-10.el8.x86_64
  - nothing provides libxmlb.so.1(LIBXMLB_0.1.2)(64bit) needed by gnome-software-3.36.1-10.el8.x86_64
  - nothing provides libxmlb.so.1(LIBXMLB_0.1.3)(64bit) needed by gnome-software-3.36.1-10.el8.x86_64
  - nothing provides libxmlb.so.1(LIBXMLB_0.1.4)(64bit) needed by gnome-software-3.36.1-10.el8.x86_64
  - nothing provides libxmlb.so.1(LIBXMLB_0.1.5)(64bit) needed by gnome-software-3.36.1-10.el8.x86_64
  - nothing provides libxmlb.so.1(LIBXMLB_0.1.7)(64bit) needed by gnome-software-3.36.1-10.el8.x86_64
  - nothing provides libxmlb(x86-64) >= 0.1.7 needed by gnome-software-3.36.1-10.el8.x86_64
Problem 13: cannot install the best update candidate for package gnome-settings-daemon-3.28.1-2.el8.x86_64
  - problem with installed package gnome-settings-daemon-3.28.1-2.el8.x86_64
  - nothing provides gsettings-desktop-schemas(x86-64) >= 3.32.0-4 needed by gnome-settings-daemon-3.32.0-16.el8.x86_64
Problem 14: cannot install the best update candidate for package glusterfs-cli-3.12.2-40.2.el8.x86_64
  - problem with installed package glusterfs-cli-3.12.2-40.2.el8.x86_64
  - nothing provides glusterfs-libs(x86-64) = 6.0-56.4.el8 needed by glusterfs-cli-6.0-56.4.el8.x86_64
Problem 15: cannot install the best update candidate for package glusterfs-api-3.12.2-40.2.el8.x86_64
  - problem with installed package glusterfs-api-3.12.2-40.2.el8.x86_64
  - nothing provides glusterfs-libs(x86-64) = 6.0-56.4.el8 needed by glusterfs-api-6.0-56.4.el8.x86_64
  - nothing provides glusterfs(x86-64) = 6.0-56.4.el8 needed by glusterfs-api-6.0-56.4.el8.x86_64
  - nothing provides glusterfs-client-xlators(x86-64) = 6.0-56.4.el8 needed by glusterfs-api-6.0-56.4.el8.x86_64
Problem 16: cannot install the best update candidate for package gjs-1.52.5-2.el8.x86_64
  - problem with installed package gjs-1.52.5-2.el8.x86_64
  - nothing provides libmozjs-60.so.0()(64bit) needed by gjs-1.56.2-5.el8.x86_64
  - nothing provides libmozjs-60.so.0(js)(64bit) needed by gjs-1.56.2-5.el8.x86_64
  - nothing provides mozjs60(x86-64) >= 60.9.0-4 needed by gjs-1.56.2-5.el8.x86_64
Problem 17: cannot install the best update candidate for package gdk-pixbuf2-modules-2.36.12-2.el8.x86_64
  - problem with installed package gdk-pixbuf2-modules-2.36.12-2.el8.x86_64
  - nothing provides gdk-pixbuf2(x86-64) = 2.36.12-5.el8 needed by gdk-pixbuf2-modules-2.36.12-5.el8.x86_64
Problem 18: problem with installed package flatpak-libs-1.0.6-2.el8.x86_64
  - cannot install the best update candidate for package flatpak-libs-1.0.6-2.el8.x86_64
  - nothing provides bubblewrap >= 0.4.0 needed by flatpak-libs-1.8.5-4.el8_4.x86_64
  - nothing provides bubblewrap >= 0.4.0 needed by flatpak-libs-1.8.5-5.el8_5.x86_64
Problem 19: problem with installed package flatpak-1.0.6-2.el8.x86_64
  - cannot install the best update candidate for package flatpak-1.0.6-2.el8.x86_64
  - nothing provides bubblewrap >= 0.4.0 needed by flatpak-1.8.5-4.el8_4.x86_64
  - nothing provides bubblewrap >= 0.4.0 needed by flatpak-1.8.5-5.el8_5.x86_64
Problem 20: cannot install the best update candidate for package dbus-x11-1:1.12.8-7.el8.x86_64
  - problem with installed package dbus-x11-1:1.12.8-7.el8.x86_64
  - nothing provides dbus-daemon = 1:1.12.8-14.el8 needed by dbus-x11-1:1.12.8-14.el8.x86_64
Problem 21: cannot install the best update candidate for package cups-client-1:2.2.6-25.el8.x86_64
  - problem with installed package cups-client-1:2.2.6-25.el8.x86_64
  - nothing provides cups-libs(x86-64) = 1:2.2.6-40.el8 needed by cups-client-1:2.2.6-40.el8.x86_64
Problem 22: cannot install the best update candidate for package cups-1:2.2.6-25.el8.x86_64
  - problem with installed package cups-1:2.2.6-25.el8.x86_64
  - nothing provides cups-libs(x86-64) = 1:2.2.6-40.el8 needed by cups-1:2.2.6-40.el8.x86_64
Problem 23: cannot install the best update candidate for package criu-3.10-7.el8.x86_64
  - problem with installed package criu-3.10-7.el8.x86_64
  - nothing provides libnftables.so.1()(64bit) needed by criu-3.15-3.module_el8.5.0+890+6b136101.x86_64
Problem 24: cannot install the best update candidate for package container-selinux-2:2.94-1.git1e99f1d.module_el8.0.0+58+91b614e7.noarch
  - problem with installed package container-selinux-2:2.94-1.git1e99f1d.module_el8.0.0+58+91b614e7.noarch
  - nothing provides selinux-policy >= 3.14.3-9.el8 needed by container-selinux-2:2.167.0-1.module_el8.5.0+911+f19012f9.noarch
  - nothing provides selinux-policy-base >= 3.14.3-9.el8 needed by container-selinux-2:2.167.0-1.module_el8.5.0+911+f19012f9.noarch
  - nothing provides selinux-policy-targeted >= 3.14.3-9.el8 needed by container-selinux-2:2.167.0-1.module_el8.5.0+911+f19012f9.noarch
Problem 25: cannot install the best update candidate for package cockpit-storaged-184.1-1.el8.noarch
  - problem with installed package cockpit-storaged-184.1-1.el8.noarch
  - nothing provides cockpit-shell >= 186 needed by cockpit-storaged-251.1-1.el8.noarch
Problem 26: cannot install the best update candidate for package cockpit-packagekit-184.1-1.el8.noarch
  - problem with installed package cockpit-packagekit-184.1-1.el8.noarch
  - nothing provides cockpit-bridge >= 186 needed by cockpit-packagekit-251.1-1.el8.noarch
Problem 27: cannot install the best update candidate for package centos-backgrounds-80.5-2.el8.noarch
  - problem with installed package centos-backgrounds-80.5-2.el8.noarch
  - nothing provides centos-logos = 85.8-2.el8 needed by centos-backgrounds-85.8-2.el8.noarch
Problem 28: problem with installed package qemu-kvm-15:2.12.0-64.module_el8.0.0+44+94c1b039.2.x86_64
  - cannot install the best update candidate for package qemu-kvm-15:2.12.0-64.module_el8.0.0+44+94c1b039.2.x86_64
  - package qemu-kvm-15:4.2.0-59.module_el8.5.0+1002+36725df2.x86_64 requires qemu-kvm-core = 15:4.2.0-59.module_el8.5.0+1002+36725df2, but none of the providers can be installed
  - package qemu-kvm-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64 requires qemu-kvm-core = 15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1, but none of the providers can be installed
  - nothing provides libseccomp >= 2.4.0 needed by qemu-kvm-core-15:4.2.0-59.module_el8.5.0+1002+36725df2.x86_64
  - nothing provides libseccomp >= 2.4.0 needed by qemu-kvm-core-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64
Problem 29: problem with installed package qemu-kvm-block-gluster-15:2.12.0-64.module_el8.0.0+44+94c1b039.2.x86_64
  - cannot install the best update candidate for package qemu-kvm-block-gluster-15:2.12.0-64.module_el8.0.0+44+94c1b039.2.x86_64
  - package qemu-kvm-block-gluster-15:4.2.0-59.module_el8.5.0+1002+36725df2.x86_64 requires libgfapi.so.0(GFAPI_6.0)(64bit), but none of the providers can be installed
  - package qemu-kvm-block-gluster-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64 requires libgfapi.so.0(GFAPI_6.0)(64bit), but none of the providers can be installed
  - nothing provides glusterfs-libs(x86-64) = 6.0-56.4.el8 needed by glusterfs-api-6.0-56.4.el8.x86_64
  - nothing provides glusterfs(x86-64) = 6.0-56.4.el8 needed by glusterfs-api-6.0-56.4.el8.x86_64
  - nothing provides glusterfs-client-xlators(x86-64) = 6.0-56.4.el8 needed by glusterfs-api-6.0-56.4.el8.x86_64
Problem 30: cannot install the best update candidate for package gvfs-1.36.2-1.el8.x86_64
  - problem with installed package gvfs-1.36.2-1.el8.x86_64
  - package gvfs-1.36.2-11.el8.x86_64 requires gsettings-desktop-schemas >= 3.28.1-2, but none of the providers can be installed
  - gsettings-desktop-schemas-3.32.0-6.el8.i686 has inferior architecture
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)


Thanks,
Saravanan Natarajan

**Comment by sharans147** [comment]
Hi Team,

We have tried below command and got below error

dnf install centos-linux-repos -y
Last metadata expiration check: 0:16:03 ago on Tue 07 May 2024 05:40:59 PM IST.
No match for argument: centos-linux-repos
Error: Unable to find a match: centos-linux-repos
[root@gitlab-app ~]# yum update
Last metadata expiration check: 0:16:11 ago on Tue 07 May 2024 05:40:59 PM IST.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by scoter-oracle** [comment]
I suspect that you have a customized yum configuration on your CentOS machine; this is my test environment:

[root@centos8 ~]# cat /etc/centos-release
CentOS Linux release 8.0.1905 (Core)

[root@centos8 ~]# dnf info centos-linux-repos
Last metadata expiration check: 0:00:31 ago on Tue 07 May 2024 12:50:49 PM UTC.
Available Packages
Name         : centos-linux-repos
Version      : 8
Release      : 3.el8
Arch         : noarch
Size         : 20 k
Source       : centos-repos-8-3.el8.src.rpm
Repo         : BaseOS
Summary      : CentOS Linux package repositories
URL          : https://centos.org
License      : GPLv2
Description  : This package provides the package repository files for CentOS Linux.

and this is the installation of that package on a 8.0 CentOS system:

[root@centos8 ~]# dnf install -y centos-linux-repos
Last metadata expiration check: 0:01:18 ago on Tue 07 May 2024 12:50:49 PM UTC.
Dependencies resolved.
========================================================================================================================================================================================
 Package                                             Arch                                  Version                                          Repository                             Size
========================================================================================================================================================================================
Installing:
 centos-linux-repos                                  noarch                                8-3.el8                                          BaseOS                                 20 k
Installing dependencies:
 centos-gpg-keys                                     noarch                                1:8-3.el8                                        BaseOS                                 12 k
 centos-linux-release                                noarch                                8.5-1.2111.el8                                   BaseOS                                 22 k
     replacing  centos-release.x86_64 8.0-0.1905.0.9.el8

Transaction Summary
========================================================================================================================================================================================
Install  3 Packages

Total download size: 54 k
Downloading Packages:
(1/3): centos-gpg-keys-8-3.el8.noarch.rpm                                                                                                                11 kB/s |  12 kB     00:01
(2/3): centos-linux-release-8.5-1.2111.el8.noarch.rpm                                                                                                    21 kB/s |  22 kB     00:01
(3/3): centos-linux-repos-8-3.el8.noarch.rpm                                                                                                             18 kB/s |  20 kB     00:01
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                    50 kB/s |  54 kB     00:01
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                1/1
  Running scriptlet: centos-gpg-keys-1:8-3.el8.noarch                                                                                                                               1/1
  Installing       : centos-gpg-keys-1:8-3.el8.noarch                                                                                                                               1/4
  Installing       : centos-linux-release-8.5-1.2111.el8.noarch                                                                                                                     2/4
  Installing       : centos-linux-repos-8-3.el8.noarch                                                                                                                              3/4
  Obsoleting       : centos-release-8.0-0.1905.0.9.el8.x86_64                                                                                                                       4/4
warning: /etc/yum.repos.d/CentOS-fasttrack.repo saved as /etc/yum.repos.d/CentOS-fasttrack.repo.rpmsave
warning: /etc/yum.repos.d/CentOS-centosplus.repo saved as /etc/yum.repos.d/CentOS-centosplus.repo.rpmsave
warning: /etc/yum.repos.d/CentOS-Sources.repo saved as /etc/yum.repos.d/CentOS-Sources.repo.rpmsave
warning: /etc/yum.repos.d/CentOS-PowerTools.repo saved as /etc/yum.repos.d/CentOS-PowerTools.repo.rpmsave
warning: /etc/yum.repos.d/CentOS-Extras.repo saved as /etc/yum.repos.d/CentOS-Extras.repo.rpmsave
warning: /etc/yum.repos.d/CentOS-Base.repo saved as /etc/yum.repos.d/CentOS-Base.repo.rpmsave
warning: /etc/yum.repos.d/CentOS-AppStream.repo saved as /etc/yum.repos.d/CentOS-AppStream.repo.rpmsave

  Running scriptlet: centos-release-8.0-0.1905.0.9.el8.x86_64                                                                                                                       4/4
  Verifying        : centos-gpg-keys-1:8-3.el8.noarch                                                                                                                               1/4
  Verifying        : centos-linux-release-8.5-1.2111.el8.noarch                                                                                                                     2/4
  Verifying        : centos-release-8.0-0.1905.0.9.el8.x86_64                                                                                                                       3/4
  Verifying        : centos-linux-repos-8-3.el8.noarch                                                                                                                              4/4

Installed:
  centos-linux-repos-8-3.el8.noarch                         centos-gpg-keys-1:8-3.el8.noarch                         centos-linux-release-8.5-1.2111.el8.noarch

Complete!

**Comment by scoter-oracle** [comment]
It is successfully migrated to Oracle Linux as soon as your systems boots with the updated kernel coming from Oracle Linux repositories and the files /etc/*release files

**Comment by sharans147** [comment]
Hi Scoter,

We could see mixed packages on the server. kindly see below the details.




 
it seems the server is running with mixed packages. 
 
[root@gitlab-app ~]# uname -r

5.4.17-2136.330.7.1.el8uek.x86_64

[root@gitlab-app ~]# yum list installed |wc -l

1444

[root@gitlab-app ~]# yum list installed |grep ol8 |wc -l

1394

[root@gitlab-app ~]# yum list installed |grep -i "@appstream" |wc -l

38

=====================================
[root@gitlab-app ~]# yum list installed |grep -i "@appstream"

centos-indexhtml.noarch                           8.0-0.el8                                      @AppStream

insights-client.noarch                            3.0.5-4.el8                                    @AppStream

libiscsi.x86_64                                   1.18.0-8.module_el8.5.0+746+bbd5d70c           @AppStream

libssh2.x86_64                                    1.8.0-8.module_el8.0.0+189+f9babebb.1          @AppStream

libvirt-daemon.x86_64                             6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-daemon-config-network.x86_64              6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-daemon-driver-interface.x86_64            6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-daemon-driver-network.x86_64              6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-daemon-driver-nodedev.x86_64              6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-daemon-driver-nwfilter.x86_64             6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-daemon-driver-qemu.x86_64                 6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-daemon-driver-secret.x86_64               6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-daemon-driver-storage.x86_64              6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-daemon-driver-storage-core.x86_64         6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-daemon-driver-storage-disk.x86_64         6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-daemon-driver-storage-gluster.x86_64      6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-daemon-driver-storage-iscsi.x86_64        6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-daemon-driver-storage-iscsi-direct.x86_64 6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-daemon-driver-storage-logical.x86_64      6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-daemon-driver-storage-mpath.x86_64        6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-daemon-driver-storage-rbd.x86_64          6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-daemon-driver-storage-scsi.x86_64         6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-daemon-kvm.x86_64                         6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

libvirt-libs.x86_64                               6.0.0-37.module_el8.5.0+1002+36725df2          @AppStream

netcf-libs.x86_64                                 0.2.8-12.module_el8.5.0+746+bbd5d70c           @AppStream

qemu-guest-agent.x86_64                           15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1     @AppStream

qemu-img.x86_64                                   15:2.12.0-65.module_el8.0.0+189+f9babebb.5     @AppStream

qemu-kvm.x86_64                                   15:2.12.0-65.module_el8.0.0+189+f9babebb.5     @AppStream

qemu-kvm-block-curl.x86_64                        15:2.12.0-65.module_el8.0.0+189+f9babebb.5     @AppStream

qemu-kvm-block-gluster.x86_64                     15:2.12.0-65.module_el8.0.0+189+f9babebb.5     @AppStream

qemu-kvm-block-iscsi.x86_64                       15:2.12.0-65.module_el8.0.0+189+f9babebb.5     @AppStream

qemu-kvm-block-rbd.x86_64                         15:2.12.0-65.module_el8.0.0+189+f9babebb.5     @AppStream

qemu-kvm-block-ssh.x86_64                         15:2.12.0-65.module_el8.0.0+189+f9babebb.5     @AppStream

qemu-kvm-common.x86_64                            15:2.12.0-65.module_el8.0.0+189+f9babebb.5     @AppStream

qemu-kvm-core.x86_64                              15:2.12.0-65.module_el8.0.0+189+f9babebb.5     @AppStream

seabios-bin.noarch                                1.13.0-2.module_el8.5.0+746+bbd5d70c           @AppStream

seavgabios-bin.noarch                             1.13.0-2.module_el8.5.0+746+bbd5d70c           @AppStream

sgabios-bin.noarch                                1:0.20170427git-3.module_el8.5.0+746+bbd5d70c  @AppStream

**Comment by scoter-oracle** [comment]
this is expected.
