### ISSUE TITLE
Post OS Migration- server packages listed mixed el7 and ol7 

### ISSUE THREAD

**Issue by srinidks** [oracle/centos2ol#173]
Hi Team,
Recently we converted OS from Centos7.9 to Oracle Linux7.9 , it seems the server is running mixed packages ol7 and el7.
Is it fine or need to update/change any configuration. 
I have followed the URL below.
https://docs.oracle.com/en/learn/switch_centos7_ol7/index.html 

[root@gitlab-db ~]# uname -r
5.4.17-2136.330.7.1.el7uek.x86_64

[root@gitlab-db ~]# yum list installed |wc -l
1782

[root@gitlab-db ~]# yum list installed |grep ol7|wc -l
516

[root@gitlab-db ~]# yum list installed |grep @base/7 |wc -l
702

[root@gitlab-db ~]# yum list installed |grep anaconda/7 |wc -l
281

[root@gitlab-db ~]# yum list installed |grep updates/7 |wc -l
195

[root@gitlab-db ~]# cat /etc/*release
Oracle Linux Server release 7.9
NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://github.com/oracle/oracle-linux"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9
Red Hat Enterprise Linux Server release 7.9 (Maipo)
Oracle Linux Server release 7.9

**Comment by totalamateurhour** [comment]
Oracle Linux 7 has many of `el7` packages, see [Oracle Linux yum server](https://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/index.html), so this is normal. Are there particular packages you are concerned about?

**Comment by tvierling** [comment]
centos2ol doesn't reinstall all packages on the system. Most versions which came from CentOS Linux 7, which have not been updated in Oracle LInux yet (so the version strings are the same in C7 and OL7), will keep their CentOS binaries until the package is either reinstalled or updated. The code for packages like this is the same, just compiled into binary form in different places.

Oracle considers those C7-originated binaries supported under OL7, so it's okay to leave them as they are. If there are specific cases you're concerned with as @totalamateurhour mentioned above, please let us know though.

**Comment by srinidks** [comment]
Hi Team, 
Thanks for the update, most of the packages installed from base/7 repo. Which was used centos7. How to get installed package from centos repository.

**Comment by tvierling** [comment]
Once you switch to OL7, you will get updates from the Oracle Linux yum repositories, which will be Oracle binaries.

The packages which did not need updates are still from CentOS (because they are not modified). These will keep running correctly.

**Comment by srinidks** [comment]
Hi Team,
Thank you for the update.
