### ISSUE TITLE
CentOS Stream release 8 - unsupported distribution

### ISSUE THREAD

**Issue by popis1** [oracle/centos2ol#177]
Hello,

I would switch CentOS 8 to Oracle linux newest version. I was download centos2ol.sh script and when i run it i have that comunication:
 `
[root@centos-v3 /]# sudo bash centos2ol.sh
Checking for required packages...
Checking your distribution...
You appear to be running an unsupported distribution.
For assistance, please open an issue via GitHub: https://github.com/oracle/centos2ol/.
`

**Comment by totalamateurhour** [comment]
It sounds like you are running Centos 8 Stream. As explained in the [README](https://github.com/oracle/centos2ol?tab=readme-ov-file#supported-versions-and-architectures), this is not a supported distribution.
