### ISSUE TITLE
Migrate from centos7.9 to ol8.8?

### ISSUE THREAD

**Issue by cc-mike63** [oracle/centos2ol#178]
Is there a parameter I can add to the script to cause centos7.9 to migrate specifically to Oracle Linux 8.8? Our app only supports that path. Any guidance much appreciated.

**Comment by tvierling** [comment]
You can migrate to OL7 *first* using this tool, and then upgrade to OL8 [via Leapp](https://docs.oracle.com/en/operating-systems/oracle-linux/8/leapp/) after that, but there is no option to "migrate specifically to OL 8.8" — you'll upgrade to the latest update level of OL8, which is currently 8.9 (and soon 8.10).

Remember that the version of the OS is "OL7" or "OL8". The number after the dot is only an update level, or patchlevel. Any system running "8.8" today is by definition not up-to-date and vulnerable to security issues, and we offer no way to migrate to out-of-date packages for that security reason.

If your application works on "8.8", then that means it also works on all later patchlevels of OL8.

**Comment by cc-mike63** [comment]
Thank you for your prompt response. We are running Ciena MCP (aka "Navigator") 7.x. Prerequisite to upgrading it to 8.x their docs mandate a migration from centos7.9 to, either, RHEL or Oracle 8.6 or 8.8. Otherwise unsupported.

**Comment by tvierling** [comment]
You mean Oracle Linux 8, not "8.6" or "8.8".

A vendor does not get to choose whether or not you install security updates. It is up to *Oracle* to guarantee application compatibility when you install OS updates, not your application vendor. If your vendor thinks that the application will run on "8.8" but not "8.9", they are in error and you should correct them. The vendor can certify a *minimum* update level (like "OL8, update level 8.8 or later"), not an exact one.

Any application which is certified to run on "8.8" is also certified, automatically by Oracle, to run on "8.9" and "8.10" because all of these are the same version: they are all just different patchlevels of OL8.

We do not offer a way to upgrade a system from OL7 to OL8, and avoid installing security updates.

**Comment by cc-mike63** [comment]
I understand. However, Ciena states in their documentation: (Ciena MCP 7.x to 8.x OS Migration)
----------------------------------------------------------------------
**Table 1. Operating system migration supported path**
From                                   To
RHEL 7.9                               RHEL 8.6/8.8
Oracle Linux 7.9                    Oracle Linux 8.6/8.8
CentOS 7.9                           RHEL/ORACLE Linux 8.6/8.8

Considerations
- CentOS 7.9 can only be migrated to RHEL/Oracle Linux 8.6/8.8.
------------------------------------------------------------------------
After installation any OS, or other updates ("bundles"), are supplied solely by Ciena; once they are vetted to work with their app.
I was informed by Ciena support that their 8.x app installer checks OS version at startup and will not run if OS version is other than ol8.6 or 8.8.

I previously downloaded the ol8.8 ISO. Can I not, instead, run the install, locally, and install ol8.8 over the centos7.9 now running on the servers? I plan to upgrade a test environment first to confirm operability.

Thank you again for your assistance.

**Comment by tvierling** [comment]
Please open a support ticket with that vendor. You should consider it unacceptable that you cannot install security updates for your OS (which would make OL8 appear as "8.9" today, and "8.10" soon). Their check for exactly "8.8" is improper and Oracle does not condone using such checks to prevent you from installing updates.

If you want to install from scratch, you are free to do it, but this will not "upgrade" the system; it will install a bare system and you will need to migrate/install your applications to it.

**Comment by cc-mike63** [comment]
I understand your point. Unfortunately, I have been fighting that battle for more than 2 years, with little success. I have to continue using the app to manage assets. And, now, have to migrate/upgrade in order to gain functionality. Thank you again for your time and guidance.
