### ISSUE TITLE
centos2ol.sh: line 167: syntax error near unexpected token `<'

### ISSUE THREAD

**Issue by graham1228** [oracle/centos2ol#18]
Looks like there is a syntax error on line 167
https://github.com/oracle/centos2ol/blob/main/centos2ol.sh#L167

**Comment by Djelibeybi** [comment]
That line has been pretty well tested. Can you confirm that this script is being run by `bash`?

**Comment by graham1228** [comment]
Here is my workflow:

        "sudo curl -O https://raw.githubusercontent.com/oracle/centos2ol/main/centos2ol.sh",
        "sudo chmod +x centos2ol.sh",
        "sudo sh centos2ol.sh",
        "sudo rm -f /var/cache/yum/timedhosts.txt"

Issue logged here:
https://github.com/oracle/centos2ol/issues/18 <https://github.com/oracle/centos2ol/issues/18>

Thanks,
Robert Graham
graham.robert.j@gmail.com <mailto:graham.robert.j@gmail.com>

**Comment by graham1228** [comment]
Is bash now a requirement for the script? Previously the script worked when executed with sh.

**Comment by Djelibeybi** [comment]
You can remove the `sudo chmod +x centos2ol.sh` line as that isn't required. 

Can you please change `sudo sh centos2ol.sh` with `sudo bash centos2ol.sh`? The script requires `bash` to handle the associative arrays needed to map modules from CentOS 8 to Oracle Linux 8.

**Comment by graham1228** [comment]
Switching from `sh` to `bash` did the trick. Would it be possible to release a 0.1 version of the repo, so I can lock down to a known good version? We use this script in automation and I would prefer to not pull it from the master branch each time.

**Comment by Djelibeybi** [comment]
I'm not sure if we're ready to tag a release yet, as there are still open issues that we need to resolve, in particular the OpenJDK alternatives thing. Hopefully soon, though.

**Comment by Djelibeybi** [comment]
As this was resolved by using `bash`, I am going to close this issue.
