### ISSUE TITLE
multiple packages are providing redhat-release

### ISSUE THREAD

**Issue by sk1561** [oracle/centos2ol#22]
I'm trying to covert centos 8 to oracle linux.
When execute centos2ol.sh, I got an error message.

> Checking for required packages...
> Checking your distribution...
> Could not determine your distribution because multiple
> packages are providing redhat-release:
> centos-linux-release-8.3-1.2011.el8.noarch
> redhat-release-8.3-1.0.0.1.el8.x86_64
> redhat-release-8.3-1.0.0.1.el8.x86_64

What's that?

**Comment by Djelibeybi** [comment]
You appear to have multiple packages all providing the same thing. This shouldn't happen with a standard install of CentOS 8. Can you provide some background on how this server was installed or where it's running?

**Comment by mark-au** [comment]
Can we see the output of `yum info redhat-release`? I'd expect `centos-linux-release` to be present but not `redhat-release`

**Comment by sk1561** [comment]
Thank your reply.
It's my mistake.
Edited repos were cause.
I solved the problem using original repos.
Thanks.

**Comment by Djelibeybi** [comment]
Glad you got it working.
