### ISSUE TITLE
centos2ol.sh: line 7: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by anark1a** [oracle/centos2ol#23]
I have done a fresh install of CentOS 8 in Contabo VPS I download the centos2ol.sh script to try to convert it to Oracle Linux but I get the following errors

<p>
centos2ol.sh: line 7: syntax error near unexpected token `newline'
<p>
centos2ol.sh: line 7: `<!DOCTYPE html>'

**Comment by Djelibeybi** [comment]
How are you downloading the script? This feels like a character encoding issue which can happen if you download using Windows, for example.

**Comment by anark1a** [comment]
> How are you downloading the script? This feels like a character encoding issue which can happen if you download using Windows, for example.

I don't remember the last time I used a Windows machine, maybe 16 or 18 years I download the script using wget

**Comment by Djelibeybi** [comment]
If it's not character encoding, maybe the wrong shell interpreter. Are you sure you're  running it with `bash`?

**Comment by Lin-Buo-Ren** [comment]
IIRC loading a script using the `sh` command will make Bash operate in POSIX-sh compatibility mode, which may cause problems, just my 2 cents...

**Comment by anark1a** [comment]
> If it's not character encoding, maybe the wrong shell interpreter. Are you sure you're running it with `bash`?

Yes I'm running it with bash but it gives the same error it does no matter if you try to run it using bash, sh or ./

**Comment by Djelibeybi** [comment]
Except I can't reproduce this no matter whether I use bash, sh or ./ -- it works with all three. Can you provide the content of `/etc/os-release` and `uname -a`? We're obviously missing something, now we just have to work out what.

**Comment by anark1a** [comment]
> Except I can't reproduce this no matter whether I use bash, sh or ./ -- it works with all three. Can you provide the content of `/etc/os-release` and `uname -a`? We're obviously missing something, now we just have to work out what.

Solved

**Comment by Djelibeybi** [comment]
> Solved

Would you mind telling us how, just in case this comes up again?

**Comment by fregiventum** [comment]
I had the same issue.  What it was for me was that I right-clicked on the hyperlink in the "Either clone this repository or download the [centos2ol.sh](https://github.com/oracle/centos2ol/blob/main/centos2ol.sh) script." line and then did a wget for that hyperlink.  Rather than this downloading the script, it downloaded the web page for acquiring the script, thus the errors:

```
./centos2ol.sh: line 7: syntax error near unexpected token `newline'
./centos2ol.sh: line 7: `<!DOCTYPE html>'
```

I deleted the file, and then actually downloaded the script directly. :)

I thought I'd share since this is the only hit for the error, and it was annoying to be simply "solved" without explanation.

**Comment by Djelibeybi** [comment]
Oh, that makes sense! I've submitted a PR to fix that.

**Comment by fregiventum** [comment]
Now to figure out why I'm getting a dracut timeout after conversion. ;)

**Comment by fregiventum** [comment]
Looks good now Avi!  Thanks.  I also edited my initial posting's hyperlink, just so the old link isn't hanging around there too. :)
