### ISSUE TITLE
bring back subscription-manager

### ISSUE THREAD

**Issue by lentferj** [oracle/centos2ol#25]
It would be really, really nice if subscription-manager could be re-added to Oracle Linux 8, so organisations using Foreman/Katello could (easily) make the switch.

**Comment by Djelibeybi** [comment]
Yes, I know. I'm working on it.

**Comment by Djelibeybi** [comment]
I'm going to close this issue as it's outside the scope of this repo. I'm still working on trying to get the RPMs released officially, but until then, I've written up some notes on how to build them yourself for both Oracle Linux 7 and 8: https://omg.dje.li/2021/01/building-subscription-manager-rpms-for-oracle-linux/
