### ISSUE TITLE
CentOS HighAvailability and OL8_AddOns do not have the same content

### ISSUE THREAD

**Issue by lentferj** [oracle/centos2ol#26]
In this line CentOS8-HighAvailability gets swapped to OL8_AddOns, but OL8_AddOns is missing a lot of the packages found in CentOS8-HighAvailability, e.g. corosync-qnetd and corosync-qdevice. If you are using any of those a switch won't be possible.
https://github.com/oracle/centos2ol/blob/9a85cf760146efd26baa667e3f400d2794eecb8d/centos2ol.sh#L415

The above mentioned packages still existed in OL7 it seems. Is there another place to get them from for OL8?

**Comment by Djelibeybi** [comment]
Will look into this when I'm back at work in January. Thanks for the report.

**Comment by Djelibeybi** [comment]
We're in the process of releasing those two RPMs. I'll review the CentOS HA repo and find any other missing ones when I'm back home in a few days.

**Comment by honglinsu** [comment]
corosync-qnetd and corosync-qdevice were released to the Oracle Linux 8 addons channel: 
https://yum.oracle.com/repo/OracleLinux/OL8/addons/x86_64/index.html

**Comment by Djelibeybi** [comment]
Thanks @honglinsu. 

@lentferj, If you have any further questions or issues with HA, please open a new issue.
