### ISSUE TITLE
Migrating IPA server without extra repos

### ISSUE THREAD

**Issue by maverick85** [oracle/centos2ol#27]
Hi,

We have tested this script with IPA server replicas.
It appears to rollout correctly except when it reaches the following package:

`oracle-logos-ipa` which conflicts with `centos-logos-ipa`.
We retried by uninstalling `centos-logos-ipa` using `rpm -e --nodeps ...` and on the next run it failed with conflicts with `centos-logos-httpd`.

**Comment by michalgutowski** [comment]
I cannot reproduce this on my end. The script already contains dedicated `dnf swap` commands for both `centos-logos-ipa` and `centos-logos-http` packages and I can see these are being swapped correctly in my test environment (centos8.3). 

Would you be able to provide a bit more information on how you installed the IPA server? If possible please re-run the script in a debug option: `sudo bash -x centos2ol.sh -V` - this will generate more console output as well as create files with lists of rpms before and after the switch in /var/tmp.

**Comment by Djelibeybi** [comment]
Closing due to lack of response. If you're still having an issue, please reopen this issue.

**Comment by maverick85** [comment]
Hi Djelibeybi I'm sorry for the lack of response, however we didn't overcome this issue.
What we ended up to do was to create new replicas, promote to master and then remove the old CentOS machine.

I'm sorry we didn't ran it with debug option.
