### ISSUE TITLE
Report non-OracleLinux RPMs after conversion for sysadmin consideration

### ISSUE THREAD

**Issue by mark-au** [oracle/centos2ol#3]
A conversion should not automatically remove non-Oracle RPMs but we should inform a user of the systems state.
As seen in #2 a user may have RPMs from CentOS and OracleLinux installed and the system operate normally.

In the real world it's natural for a system to hold RPMs from different vendors, for transparency we should inform the sysadmin what they are to highlight any bugs/edge cases in this tool.

This issue should not be addressed until after #2 to avoid information overload

**Comment by zbrode** [comment]
General idea for identifying this content:
`rpm -qa --qf "%{NAME}|%{VERSION}|%{RELEASE}|%{VENDOR}|%{PACKAGER}\n" |grep -vi oracle |grep -v gpg-pubkey | sort`
