### ISSUE TITLE
Option -r is not recognised and the script errors out if used

### ISSUE THREAD

**Issue by Sergong** [oracle/centos2ol#32]
Hi,
When running the script with the -r option, it currently errors out with:
`option requires an argument`

According to the usage section -r is a switch and should not require an argument. Looking at the script, the line with getopts:
`while getopts "hr:V" option; do` 
has a colon, which would signify an argument is required, hence the error. This line should be:
`while getopts "hrV" option; do`

Thanks,
Serge

**Comment by Djelibeybi** [comment]
Thanks for the report. I could've sworn I removed the colon last time, but I guess not. :)
