### ISSUE TITLE
Issue with conversion after ssh session Dropped.

### ISSUE THREAD

**Issue by tpopchock** [oracle/centos2ol#4]
Hello,

I made a mistake and didn't kick off an additional screen and lost my ssh session right after I kicked off the centos2ol.sh script.  I was on CentOS 7.7 and now my cat /etc/redhat-release shows Red Hat Enterprise Linux Server release 7.9 (Maipo).  I am providing the following information per support's request.  

[root@hermes yum.repos.d]# rpm -qa | grep release
redhat-release-server-7.9-3.0.1.el7.x86_64
elrepo-release-7.0-5.el7.elrepo.noarch
oraclelinux-release-7.9-1.0.9.el7.x86_64
epel-release-7-12.noarch
oraclelinux-release-el7-1.0-13.1.el7.x86_64

[root@hermes yum.repos.d]# cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9

a uname -a command gives me Linux hermes.localdomain 5.0.9-1.el7.elrepo.x86_64 #1 SMP Sat Apr 20 09:03:57 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

I don't seem to have any valid .repo files they've all been appended .disabled  The switch-to-oraclelinux.repo file appears to be webcode and not a repo file. 

Thank you for your help.

**Comment by Djelibeybi** [comment]
The system has switched to Oracle Linux but hasn't completed the `distro-sync`.

To verify, can you please check the output from `rpm -qi centos-logos`? If it returns `package centos-logos is not installed` then run the following:

```bash
$ cd /etc/yum.repos.d/
$ sudo curl -o switch-to-oraclelinux.repo https://yum.oracle.com/public-yum-ol7.repo
$ sudo yum distro-sync
$ sudo rm -f /etc/yum.repos.d/switch-to-oraclelinux.repo
```

If the `switch-to-oraclelinux.repo` file turns out to be HTML again, please post the HTML so we can try and work out where it's coming from. Though, I would suggest checking it first incase it's coming from a corporate proxy.

**Comment by tpopchock** [comment]
Thank you again, I am really impressed with your support.  I kicked off the first couple command and can confirm the .repo is correct.  I have some issues with dependencies when I run the distro-sync and will list them below.  I can dig through those too.
--> Processing Dependency: oracle(kernel-sig-key) >= 202007 for package: shim-x64-15-2.0.9.el7.x86_64--> Finished Dependency ResolutionError: Package: shim-x64-15-2.0.9.el7.x86_64 (ol7_latest)           Requires: oracle(kernel-sig-key) >= 202007Error: Package: abrt-retrace-client-2.1.11-57.el7.centos.x86_64 (@base/7)           Requires: abrt = 2.1.11-57.el7.centos           Removing: abrt-2.1.11-57.el7.centos.x86_64 (@base/7)               abrt = 2.1.11-57.el7.centos           Updated By: abrt-2.1.11-60.0.1.el7.x86_64 (ol7_latest)               abrt = 2.1.11-60.0.1.el7           Available: abrt-2.1.11-50.0.1.el7.x86_64 (ol7_latest)               abrt = 2.1.11-50.0.1.el7           Available: abrt-2.1.11-52.0.1.el7.x86_64 (ol7_latest)               abrt = 2.1.11-52.0.1.el7           Available: abrt-2.1.11-55.0.1.el7.x86_64 (ol7_latest)               abrt = 2.1.11-55.0.1.el7           Available: abrt-2.1.11-57.0.1.el7.x86_64 (ol7_latest)               abrt = 2.1.11-57.0.1.el7Error: Package: kmod-kvdo-6.1.3.23-5.0.1.el7.x86_64 (ol7_latest)           Requires: kernel(dm_put_device) = 0x412d503d           Installed: kernel-3.10.0-957.el7.x86_64 (@anaconda/7)               kernel(dm_put_device) = 0x660c95fc           Installed: kernel-ml-5.0.2-1.el7.elrepo.x86_64 (@elrepo-kernel/7)               kernel(dm_put_device) = 0xc04ad44d           Installed: kernel-ml-5.0.9-1.el7.elrepo.x86_64 (@elrepo-kernel/7)               kernel(dm_put_device) = 0x3bfa663aError: Package: libreport-plugin-mantisbt-2.1.11-53.el7.centos.x86_64 (@base/7)           Requires: libreport = 2.1.11-53.el7.centos           Removing: libreport-2.1.11-53.el7.centos.x86_64 (@base/7)               libreport = 2.1.11-53.el7.centos           Updated By: libreport-2.1.11-53.0.1.el7.x86_64 (ol7_latest)               libreport = 2.1.11-53.0.1.el7           Available: libreport-2.1.11-40.0.1.el7.i686 (ol7_latest)               libreport = 2.1.11-40.0.1.el7           Available: libreport-2.1.11-42.0.1.el7.i686 (ol7_latest)               libreport = 2.1.11-42.0.1.el7           Available: libreport-2.1.11-43.0.1.el7.i686 (ol7_latest)               libreport = 2.1.11-43.0.1.el7Error: Package: kmod-kvdo-6.1.3.23-5.0.1.el7.x86_64 (ol7_latest)           Requires: kernel(dm_register_target) = 0x979ddcc5           Installed: kernel-3.10.0-957.el7.x86_64 (@anaconda/7)               kernel(dm_register_target) = 0xfcd652d7           Installed: kernel-ml-5.0.2-1.el7.elrepo.x86_64 (@elrepo-kernel/7)               kernel(dm_register_target) = 0x2b88e42c           Installed: kernel-ml-5.0.9-1.el7.elrepo.x86_64 (@elrepo-kernel/7)               kernel(dm_register_target) = 0x0f8c9afeError: Package: libreport-centos-2.1.11-53.el7.centos.x86_64 (@base/7)           Requires: libreport-web = 2.1.11-53.el7.centos           Removing: libreport-web-2.1.11-53.el7.centos.x86_64 (@base/7)               libreport-web = 2.1.11-53.el7.centos           Updated By: libreport-web-2.1.11-53.0.1.el7.x86_64 (ol7_latest)               libreport-web = 2.1.11-53.0.1.el7           Available: libreport-web-2.1.11-40.0.1.el7.i686 (ol7_latest)               libreport-web = 2.1.11-40.0.1.el7           Available: libreport-web-2.1.11-42.0.1.el7.i686 (ol7_latest)               libreport-web = 2.1.11-42.0.1.el7           Available: libreport-web-2.1.11-43.0.1.el7.i686 (ol7_latest)               libreport-web = 2.1.11-43.0.1.el7Error: Package: libreport-plugin-mantisbt-2.1.11-53.el7.centos.x86_64 (@base/7)           Requires: libreport-web = 2.1.11-53.el7.centos           Removing: libreport-web-2.1.11-53.el7.centos.x86_64 (@base/7)               libreport-web = 2.1.11-53.el7.centos           Updated By: libreport-web-2.1.11-53.0.1.el7.x86_64 (ol7_latest)               libreport-web = 2.1.11-53.0.1.el7           Available: libreport-web-2.1.11-40.0.1.el7.i686 (ol7_latest)               libreport-web = 2.1.11-40.0.1.el7           Available: libreport-web-2.1.11-42.0.1.el7.i686 (ol7_latest)               libreport-web = 2.1.11-42.0.1.el7           Available: libreport-web-2.1.11-43.0.1.el7.i686 (ol7_latest)               libreport-web = 2.1.11-43.0.1.el7Error: Package: libreport-centos-2.1.11-53.el7.centos.x86_64 (@base/7)           Requires: libreport = 2.1.11-53.el7.centos           Removing: libreport-2.1.11-53.el7.centos.x86_64 (@base/7)               libreport = 2.1.11-53.el7.centos           Updated By: libreport-2.1.11-53.0.1.el7.x86_64 (ol7_latest)               libreport = 2.1.11-53.0.1.el7           Available: libreport-2.1.11-40.0.1.el7.i686 (ol7_latest)               libreport = 2.1.11-40.0.1.el7           Available: libreport-2.1.11-42.0.1.el7.i686 (ol7_latest)               libreport = 2.1.11-42.0.1.el7           Available: libreport-2.1.11-43.0.1.el7.i686 (ol7_latest)               libreport = 2.1.11-43.0.1.el7Error: Package: kmod-kvdo-6.1.3.23-5.0.1.el7.x86_64 (ol7_latest)           Requires: kernel(dm_get_device) = 0xa425b4a9           Installed: kernel-3.10.0-957.el7.x86_64 (@anaconda/7)               kernel(dm_get_device) = 0x304f1d09           Installed: kernel-ml-5.0.2-1.el7.elrepo.x86_64 (@elrepo-kernel/7)               kernel(dm_get_device) = 0x62d47708           Installed: kernel-ml-5.0.9-1.el7.elrepo.x86_64 (@elrepo-kernel/7)               kernel(dm_get_device) = 0x22c468ddError: Package: kmod-kvdo-6.1.3.23-5.0.1.el7.x86_64 (ol7_latest)           Requires: kernel(dm_unregister_target) = 0xeeeae71b           Installed: kernel-3.10.0-957.el7.x86_64 (@anaconda/7)               kernel(dm_unregister_target) = 0x33f324ab           Installed: kernel-ml-5.0.2-1.el7.elrepo.x86_64 (@elrepo-kernel/7)               kernel(dm_unregister_target) = 0x87aec5c4           Installed: kernel-ml-5.0.9-1.el7.elrepo.x86_64 (@elrepo-kernel/7)               kernel(dm_unregister_target) = 0xf6ef8b54 You could try using --skip-broken to work around the problem You could try running: rpm -Va --nofiles --nodigest

    On Friday, December 11, 2020, 02:55:43 PM EST, Avi Miller <notifications@github.com> wrote:  
 
 


The system has switched to Oracle Linux but hasn't completed the distro-sync.

To verify, can you please check the output from rpm -qi centos-logos? If it returns package centos-logos is not installed then run the following:
$ cd /etc/yum.repos.d/
$ sudo curl -o switch-to-oraclelinux.repo https://yum.oracle.com/public-yum-ol7.repo
$ sudo yum distro-sync
$ sudo rm -f /etc/yum.repos.d/switch-to-oraclelinux.repo
If the switch-to-oraclelinux.repo file turns out to be HTML again, please post the HTML so we can try and work out where it's coming from. Though, I would suggest checking it first incase it's coming from a corporate proxy.

**Comment by Djelibeybi** [comment]
You have kernels installed from `elrepo` which makes this box not-quite-CentOS. I'll add a note to the **Before you begin** section that documents the need to uninstall any kernel from `centosplus` or `elrepo` or any other repo that isn't CentOS-Base.

**Comment by Djelibeybi** [comment]
To unravel this, you'll probably need to run  `yum remove kmod-kvdo libreport*` first. Then `yum remove kernel-ml*`

**Comment by tpopchock** [comment]
Ahh I see yes I had to install an alternate kernel to fix some stability issues with the system crashing due to the AMD Ryzen chip.  Thank you for the heads up I'm sure this will fix the issue.

**Comment by tpopchock** [comment]
I can confirm that yum remove kmod-kvdo libreport* and yum remove kernel-ml* resolved the issues with the dependencies and I was able successfully complete a yum distro-sync.  Thanks again for the help, it is very appreciated!

**Comment by Djelibeybi** [comment]
You're welcome. I'll take this moment to let you know that the UEK5 and UEK6 support AMD Ryzen and AMD EPYC chips just fine because they power our Flexible E3 Shapes on Oracle Cloud Infrastructure. 

Based on your last update, I'm going to close this issue. Feel free to open a new one if you have any further questions.

**Comment by Djelibeybi** [comment]
Oh, and I've created https://github.com/oracle/centos2ol/pull/5 to make the docs more explicit about the need to remove non-CentOS kernels before switching.
