### ISSUE TITLE
Problem: module rust-toolset:ol8:8030020200807201053:9de6951e-0.x86_64 requires module(llvm-toolset:ol8), but none of the providers can be installed

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [oracle/centos2ol#49]
Problem: module rust-toolset:ol8:8030020200807201053:9de6951e-0.x86_64 requires module(llvm-toolset:ol8), but none of the providers can be installed
  - module llvm-toolset:ol8:20190604085604:9edba152-0.x86_64 conflicts with module(llvm-toolset:rhel8) provided by llvm-toolset:rhel8:8030020201104035123:30b713e6-0.x86_64
  - module llvm-toolset:rhel8:8030020201104035123:30b713e6-0.x86_64 conflicts with module(llvm-toolset:ol8) provided by llvm-toolset:ol8:20190604085604:9edba152-0.x86_64
  - module llvm-toolset:ol8:8000020190606151548:9edba152-0.x86_64 conflicts with module(llvm-toolset:rhel8) provided by llvm-toolset:rhel8:8030020201104035123:30b713e6-0.x86_64
  - module llvm-toolset:rhel8:8030020201104035123:30b713e6-0.x86_64 conflicts with module(llvm-toolset:ol8) provided by llvm-toolset:ol8:8000020190606151548:9edba152-0.x86_64
  - module llvm-toolset:ol8:8010020190802085723:9edba152-0.x86_64 conflicts with module(llvm-toolset:rhel8) provided by llvm-toolset:rhel8:8030020201104035123:30b713e6-0.x86_64
  - module llvm-toolset:rhel8:8030020201104035123:30b713e6-0.x86_64 conflicts with module(llvm-toolset:ol8) provided by llvm-toolset:ol8:8010020190802085723:9edba152-0.x86_64
  - module llvm-toolset:ol8:8020020200227200857:9edba152-0.x86_64 conflicts with module(llvm-toolset:rhel8) provided by llvm-toolset:rhel8:8030020201104035123:30b713e6-0.x86_64
  - module llvm-toolset:rhel8:8030020201104035123:30b713e6-0.x86_64 conflicts with module(llvm-toolset:ol8) provided by llvm-toolset:ol8:8020020200227200857:9edba152-0.x86_64
  - module llvm-toolset:ol8:8020020200526230845:4cda2c84-0.x86_64 conflicts with module(llvm-toolset:rhel8) provided by llvm-toolset:rhel8:8030020201104035123:30b713e6-0.x86_64
  - module llvm-toolset:rhel8:8030020201104035123:30b713e6-0.x86_64 conflicts with module(llvm-toolset:ol8) provided by llvm-toolset:ol8:8020020200526230845:4cda2c84-0.x86_64
  - module llvm-toolset:ol8:8030020200820174250:9edba152-0.x86_64 conflicts with module(llvm-toolset:rhel8) provided by llvm-toolset:rhel8:8030020201104035123:30b713e6-0.x86_64
  - module llvm-toolset:rhel8:8030020201104035123:30b713e6-0.x86_64 conflicts with module(llvm-toolset:ol8) provided by llvm-toolset:ol8:8030020200820174250:9edba152-0.x86_64

**Comment by EvgenyPrikhodko** [comment]
https://github.com/oracle/centos2ol/issues/8

**Comment by Djelibeybi** [comment]
You will need to `dnf module remove llvm-toolset:rhel8 && dnf reset module llvm-toolset` before you can run `dnf module install llvm-toolset:ol8` (or anything that depends on it.
