### ISSUE TITLE
dnf module install virt

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [oracle/centos2ol#50]
Azure CLI                                                                                                                                                                                                    8.3 MB/s |  18 MB     00:02
Docker CE Stable - x86_64                                                                                                                                                                                    107 kB/s | 7.8 kB     00:00
Extra Packages for Enterprise Linux Modular 8 - x86_64                                                                                                                                                       361 kB/s | 537 kB     00:01
Extra Packages for Enterprise Linux 8 - x86_64                                                                                                                                                               3.2 MB/s | 8.8 MB     00:02
nginx stable repo                                                                                                                                                                                            136 kB/s |  20 kB     00:00
Oracle Linux 8 BaseOS Latest (x86_64)                                                                                                                                                                         73 MB/s |  29 MB     00:00
Oracle Linux 8 Application Stream (x86_64)                                                                                                                                                                    59 MB/s |  22 MB     00:00
PostgreSQL common RPMs for RHEL/CentOS 8 - x86_64                                                                                                                                                            988 kB/s | 534 kB     00:00
PostgreSQL 13 for RHEL/CentOS 8 - x86_64                                                                                                                                                                     445 kB/s | 218 kB     00:00
PostgreSQL 12 for RHEL/CentOS 8 - x86_64                                                                                                                                                                     796 kB/s | 410 kB     00:00
PostgreSQL 11 for RHEL/CentOS 8 - x86_64                                                                                                                                                                     1.0 MB/s | 606 kB     00:00
PostgreSQL 10 for RHEL/CentOS 8 - x86_64                                                                                                                                                                     850 kB/s | 422 kB     00:00
PostgreSQL 9.6 for RHEL/CentOS 8 - x86_64                                                                                                                                                                    811 kB/s | 429 kB     00:00
PostgreSQL 9.5 for RHEL/CentOS 8 - x86_64                                                                                                                                                                    654 kB/s | 365 kB     00:00
Latest Unbreakable Enterprise Kernel Release 6 for Oracle Linux 8 (x86_64)                                                                                                                                    57 MB/s |  13 MB     00:00
Installing module 'virt:rhel' from Fail-Safe repository @modulefailsafe is not allowed
No default profiles for module virt:rhel. Available profiles: common
Error: Installing module from Fail-Safe repository is not allowed

**Comment by Djelibeybi** [comment]
It's `dnf module install virt:ol` in Oracle Linux. You can see a list of the modules with `dnf module list`.

**Comment by EvgenyPrikhodko** [comment]
dnf module disable virt:rhel

**Comment by Djelibeybi** [comment]
This line `Installing module 'virt:rhel' from Fail-Safe repository @modulefailsafe is not allowed` implies that you have packages from the `virt` module installed, so you either have to remove them or switch the module stream so that you can continue to get updates for them.
