### ISSUE TITLE
Where to see the list of conf file updates

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [oracle/centos2ol#55]
Where can I see the list of files, for example, migration changes the file?

```
httpd -t
httpd: Syntax error on line 42 of /etc/httpd/conf/httpd.conf: Cannot load modules/mod_authz_default.so into server: /etc/httpd/modules/mod_authz_default.so: cannot open shared object file: No such file or directory

```

**Comment by Djelibeybi** [comment]
Install `rpmconf` from the EPEL repository. It will find all the config files that may need updating.

**Comment by EvgenyPrikhodko** [comment]
It is possible to view the list of updated files in the log

**Comment by Djelibeybi** [comment]
No, because they are not known to the switch process. You would need to use `rpmconf` or scan the filesystem for any `.rpmnew` files.

**Comment by EvgenyPrikhodko** [comment]
Thanks for the answer.
