### ISSUE TITLE
Failed to start dnf makecache.

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [oracle/centos2ol#56]
CentOS 8.
Please tell me what caused this message?

**Comment by Djelibeybi** [comment]
I have no idea. This is not a CentOS support source. If you're having problems with CentOS, you'll need to use their support.

**Comment by EvgenyPrikhodko** [comment]
This message appeared after migrating to Oracle Linux

**Comment by Djelibeybi** [comment]
Where? Please provide the _exact_ command you ran and the _entire_ output of that command.

**Comment by Djelibeybi** [comment]
Is this still an issue? If not, please close it.
