### ISSUE TITLE
Centos 7 upgrade errors out

### ISSUE THREAD

**Issue by compuwizz** [oracle/centos2ol#61]
The script errors out with a python dependency problem when trying to upgrade from Centos 7. The upgrade script was run after doing a yum update on the system and rebooting. yum distro-sync provides the same error output.

---> Package python.x86_64 0:2.7.5-90.el7 will be updated
--> Processing Dependency: python = 2.7.5-90.el7 for package: python-tools-2.7.5-90.el7.x86_64
--> Processing Dependency: python = 2.7.5-90.el7 for package: tkinter-2.7.5-90.el7.x86_64
--> Finished Dependency Resolution
Error: Package: python-tools-2.7.5-90.el7.x86_64 (@updates/7)
           Requires: python = 2.7.5-90.el7
           Removing: python-2.7.5-90.el7.x86_64 (@updates/7)
               python = 2.7.5-90.el7
           Updated By: python-2.7.5-90.0.1.el7.x86_64 (ol7_latest)
               python = 2.7.5-90.0.1.el7
           Available: python-2.7.5-68.0.1.el7.x86_64 (ol7_latest)
               python = 2.7.5-68.0.1.el7
           Available: python-2.7.5-69.0.1.el7_5.x86_64 (ol7_latest)
               python = 2.7.5-69.0.1.el7_5
           Available: python-2.7.5-76.0.1.el7.x86_64 (ol7_latest)
               python = 2.7.5-76.0.1.el7
           Available: python-2.7.5-77.0.1.el7_6.x86_64 (ol7_latest)
               python = 2.7.5-77.0.1.el7_6
           Available: python-2.7.5-79.0.1.el7_6.x86_64 (ol7_latest)
               python = 2.7.5-79.0.1.el7_6
           Available: python-2.7.5-80.0.1.el7_6.x86_64 (ol7_latest)
               python = 2.7.5-80.0.1.el7_6
           Available: python-2.7.5-86.0.1.el7.x86_64 (ol7_latest)
               python = 2.7.5-86.0.1.el7
           Available: python-2.7.5-86.0.3.el7.x86_64 (ol7_latest)
               python = 2.7.5-86.0.3.el7
           Available: python-2.7.5-88.0.1.el7.x86_64 (ol7_latest)
               python = 2.7.5-88.0.1.el7
           Available: python-2.7.5-89.0.1.el7.x86_64 (ol7_latest)
               python = 2.7.5-89.0.1.el7
Error: Package: tkinter-2.7.5-90.el7.x86_64 (@updates/7)
           Requires: python = 2.7.5-90.el7
           Removing: python-2.7.5-90.el7.x86_64 (@updates/7)
               python = 2.7.5-90.el7
           Updated By: python-2.7.5-90.0.1.el7.x86_64 (ol7_latest)
               python = 2.7.5-90.0.1.el7
           Available: python-2.7.5-68.0.1.el7.x86_64 (ol7_latest)
               python = 2.7.5-68.0.1.el7
           Available: python-2.7.5-69.0.1.el7_5.x86_64 (ol7_latest)
               python = 2.7.5-69.0.1.el7_5
           Available: python-2.7.5-76.0.1.el7.x86_64 (ol7_latest)
               python = 2.7.5-76.0.1.el7
           Available: python-2.7.5-77.0.1.el7_6.x86_64 (ol7_latest)
               python = 2.7.5-77.0.1.el7_6
           Available: python-2.7.5-79.0.1.el7_6.x86_64 (ol7_latest)
               python = 2.7.5-79.0.1.el7_6
           Available: python-2.7.5-80.0.1.el7_6.x86_64 (ol7_latest)
               python = 2.7.5-80.0.1.el7_6
           Available: python-2.7.5-86.0.1.el7.x86_64 (ol7_latest)
               python = 2.7.5-86.0.1.el7
           Available: python-2.7.5-86.0.3.el7.x86_64 (ol7_latest)
               python = 2.7.5-86.0.3.el7
           Available: python-2.7.5-88.0.1.el7.x86_64 (ol7_latest)
               python = 2.7.5-88.0.1.el7
           Available: python-2.7.5-89.0.1.el7.x86_64 (ol7_latest)
               python = 2.7.5-89.0.1.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Could not automatically sync with Oracle Linux repositories.
Check the output of 'yum distro-sync' to manually resolve the issue.
For assistance, please open an issue via GitHub: https://github.com/oracle/centos2ol/.

The packages with problems are:
Packages skipped because of dependency problems:
    python-2.7.5-90.0.1.el7.x86_64 from ol7_latest
    python-devel-2.7.5-90.0.1.el7.x86_64 from ol7_latest
    python-libs-2.7.5-90.0.1.el7.x86_64 from ol7_latest
    python-virtualenv-15.1.0-4.el7_8.noarch from ol7_latest

yum reinstall python python-devel python-libs
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * epel: mirror.vcu.edu
Installed package python-2.7.5-90.el7.x86_64 (from updates) not available.
Installed package python-devel-2.7.5-90.el7.x86_64 (from updates) not available.
Installed package python-libs-2.7.5-90.el7.x86_64 (from updates) not available.
Error: Nothing to do

**Comment by Djelibeybi** [comment]
Can you try removing `tkinter` manually first, i.e. `yum remove tkinter` and then see if the switch works?

**Comment by compuwizz** [comment]
That resolved it, thank you.

**Comment by Djelibeybi** [comment]
@mark-au should we add `tkinter` to the swap list? I'm fairly sure this isn't the first time this has come up.

**Comment by mark-au** [comment]
I'm not familiar with the tool but sure I'll have a look.

**Comment by mark-au** [comment]
It appears the CentOS RPM is hardcoded to require a certain version
```
[root@9132c434ecd7 /]# rpm -qR tkinter | grep python
python = 2.7.5-90.el7
```
and we ship a 2.7.5-90.0.1
```
[root@9132c434ecd7 /]# yum list python --show-duplicates
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
Installed Packages
python.x86_64                            2.7.5-90.el7                                   @updates/7
Available Packages
python.x86_64                            2.7.5-68.0.1.el7                               ol7_latest
python.x86_64                            2.7.5-69.0.1.el7_5                             ol7_latest
python.x86_64                            2.7.5-76.0.1.el7                               ol7_latest
python.x86_64                            2.7.5-77.0.1.el7_6                             ol7_latest
python.x86_64                            2.7.5-79.0.1.el7_6                             ol7_latest
python.x86_64                            2.7.5-80.0.1.el7_6                             ol7_latest
python.x86_64                            2.7.5-86.0.1.el7                               ol7_latest
python.x86_64                            2.7.5-86.0.3.el7                               ol7_latest
python.x86_64                            2.7.5-88.0.1.el7                               ol7_latest
python.x86_64                            2.7.5-89.0.1.el7                               ol7_latest
python.x86_64                            2.7.5-90.0.1.el7                               ol7_latest
```
I'll raise a PR
