### ISSUE TITLE
Do not install the UEK kernel by default

### ISSUE THREAD

**Issue by graham1228** [oracle/centos2ol#63]
Can we provide an option to not auto install the uek kernel? I have use cases where I need to convert a CentOS AMI to a RHCK Oracle Linux AMI and do not want the kernel-uek package used or installed.
As part of that please do not include the UEK repo channels by default either if not installing the UEK kernel.

**Comment by Djelibeybi** [comment]
Frankly, I'm reticent to do this because removing the UEK is so easy now on Oracle Linux 8. Also because we believe the UEK is a better kernel. Having said that, we do accept pull requests from contributors who have signed the OCA, so feel free to submit this enhancement.

**Comment by graham1228** [comment]
Who do I send the OCA to?

**Comment by Djelibeybi** [comment]
Start here: https://oca.opensource.oracle.com/

**Comment by mark-au** [comment]
I think an argument to not install/enable UEK would be good (`--no-uek`?) but I agree with @Djelibeybi that the default should remain to enable UEK.

**Comment by mark-au** [comment]
I understand you may not want to use the UEK and that's fine but out of interest why do you want to use RHCK? If you don't want to disclose it here you can contact oraclelinux-info_ww_grp@oracle.com

**Comment by graham1228** [comment]
Yeah, we have third party software that is not supported on UEK. We do utilize UEK for our database servers, but due to support agreements we also need to deploy RHCK.
Specifically IBM MQ is not supported on UEK.

I'll go ahead and submit a PR to enable a feature flag to disable the install of the UEK kernel. 

Also, I setup a kitchen testing suite to validate the changes through with inspec and vagrant boxes.....do you want me to include the testing framework as part of the PR. Not sure how you are development testing this now.

**Comment by Djelibeybi** [comment]
Could you please submit the test framework with a separate PR and with my deep, sincere and eternal thanks. 😊

**Comment by graham1228** [comment]
https://github.com/oracle/centos2ol/pull/64 closes this issue
