### ISSUE TITLE
convert offline

### ISSUE THREAD

**Issue by ndensan2029arai** [oracle/centos2ol#66]
I want you to be able to convert offline using oracle linux iso.

**Comment by Djelibeybi** [comment]
This is almost never going to be possible given how limited the package set on the ISO is. However, I think adding the option to specify a local mirror instead of using yum.oracle.com would be a good addition.

**Comment by Djelibeybi** [comment]
Sorry, didn't mean to close it. Hit the wrong button. 😂

**Comment by ndensan2029arai** [comment]
My only request is to be offline.
