### ISSUE TITLE
centos2ol.sh: line 188: syntax error near unexpected token `<'

### ISSUE THREAD

**Issue by slinkason** [oracle/centos2ol#68]
Use sh to enable the script
As a result, the following problems occurred
centos2ol.sh: line 188: syntax error near unexpected token `<'
But using ./ is normal
![photo_2021-02-23_04-09-45](https://user-images.githubusercontent.com/59037265/108764231-4c8bc900-758d-11eb-9998-cb5de92607c7.jpg)

**Comment by totalamateurhour** [comment]
Did you try running the script using bash?

**Comment by mark-au** [comment]
The tool is written using features of `bash` available on CentOS 6, 7 and 8 and won't run on `sh`. If you have issues running it with `bash` please reopen this ticket. If you'd like to change the script to also run with `sh` we welcome PR's :)

**Comment by slinkason** [comment]
Thanks for your reply
