### ISSUE TITLE
Need better redistribition terms/policy if you really want user move from centos to oracle linux.

### ISSUE THREAD

**Issue by netroby** [oracle/centos2ol#7]
Need better redistribition if you really want user move from centos to oracle linux.

Centos has many mirrors than oracle linux. 
Feel free to redistribute CentOS, without any problem about law, and sue. 

I am afraid oracle may not want to see Oracle Linux redistribute and mirror there and where place.

Oracle Linux a better choice?  well see

**Comment by totalamateurhour** [comment]
You are free to download Oracle Linux and distribute it unmodified.

https://yum.oracle.com/oracle-linux-isos.html

Download mirrors are available also:

https://community.oracle.com/tech/apps-infra/discussion/4417703/downloading-oracle-linux

**Comment by netroby** [comment]
@totalamateurhour can us setup our mirror server, and provided for public user?

**Comment by totalamateurhour** [comment]
Yes, others have been running them for many years, for example: http://mirrors.kernel.org/oracle/

As I said, we welcome you to run your own.

**Comment by netroby** [comment]
and what about the yum , did they has mirror?

**Comment by netroby** [comment]
I am not just say the iso, I mean the whole yum and packages. 

For example: 

https://mirrors.tuna.tsinghua.edu.cn/centos/

**Comment by Djelibeybi** [comment]
We host yum.oracle.com on Akamai's CDN, so I'm pretty sure it'll be fast wherever you are. However, you're more than welcome to create and host your own mirror server too.
