### ISSUE TITLE
PowerTools reponame seems to be case sensitive

### ISSUE THREAD

**Issue by wern0r** [oracle/centos2ol#71]
The declaration of the powertools repository in line 436 seems to be case sensitive. The reponame on my CentOS8 was powertools in lower case. After changing `[PowerTools]` to `[powertools]` the script worked like a charm.

**Comment by richardjohnjensen** [comment]
The change of case from **PowerTools** to **powertools** was made in the CentOS 8.3. Was your server upgraded before the conversion attempt?

**Comment by wern0r** [comment]
Yes it was an CentOS 8.3 (2011) server. Perhaps both cases should be covered by the script.
