### ISSUE TITLE
Docker-ce Installation issue

### ISSUE THREAD

**Issue by johna77** [oracle/centos2ol#80]
After successfully install to OL8 from Centos, i tried to install Docker-ce but faces many issues of dependencies.

dnf install docker-ce
Last metadata expiration check: 0:30:46 ago on Wed May 12 12:23:18 2021.
Error:
 Problem: package docker-ce-3:20.10.6-3.el8.x86_64 requires container-selinux >= 2:2.74, but none of the providers can be installed
  - cannot install the best candidate for the job
  - package container-selinux-2:2.107-2.module+el8.1.0+5440+994fc847.noarch is filtered out by modular filtering
  - package container-selinux-2:2.123.0-2.module+el8.1.0+5460+5d763c32.noarch is filtered out by modular filtering
  - package container-selinux-2:2.124.0-1.gitf958d0c.module+el8.2.0+7621+b33f33e5.noarch is filtered out by modular filtering
  - package container-selinux-2:2.124.0-1.module+el8.1.1+5502+fbec5cc6.noarch is filtered out by modular filtering
  - package container-selinux-2:2.124.0-1.module+el8.2.0+5584+b2b2d3fb.noarch is filtered out by modular filtering
  - package container-selinux-2:2.124.0-1.module+el8.2.0+5585+88100286.noarch is filtered out by modular filtering
  - package container-selinux-2:2.124.0-1.module+el8.2.0+7615+180dc822.noarch is filtered out by modular filtering
  - package container-selinux-2:2.124.0-1.module+el8.2.0+7618+3a616245.noarch is filtered out by modular filtering
  - package container-selinux-2:2.135.0-1.module+el8.2.1+7658+86e51d52.noarch is filtered out by modular filtering
  - package container-selinux-2:2.75-1.git99e2cfd.module+el8+5190+20ee9d65.noarch is filtered out by modular filtering
  - package container-selinux-2:2.75-1.git99e2cfd.module+el8+5201+6423ecab.noarch is filtered out by modular filtering
  - package container-selinux-2:2.94-1.git1e99f1d.module+el8.0.0+5214+b7869c3a.noarch is filtered out by modular filtering
  - package container-selinux-2:2.94-1.git1e99f1d.module+el8.0.0+5215+77f672ad.noarch is filtered out by modular filtering
  - package container-selinux-2:2.94-1.git1e99f1d.module+el8.0.0+5336+de35ffea.noarch is filtered out by modular filtering
  - package container-selinux-2:2.94-1.git1e99f1d.module+el8.0.0+5337+91623acb.noarch is filtered out by modular filtering
  - package container-selinux-2:2.94-1.git1e99f1d.module+el8.0.0.z+5239+bd2c200f.noarch is filtered out by modular filtering
  - package container-selinux-2:2.94-1.git1e99f1d.module+el8.1.0+5440+42cffa37.noarch is filtered out by modular filtering
  - package container-selinux-2:2.144.0-1.module+el8.3.0+7866+f387f528.noarch is filtered out by modular filtering
  - package container-selinux-2:2.124.0-1.gitf958d0c.module+el8.3.0+7864+d0e2eddf.noarch is filtered out by modular filtering
  - package container-selinux-2:2.130.0-1.module+el8.3.0+7863+c7f8774f.noarch is filtered out by modular filtering
  - package container-selinux-2:2.130.0-1.module+el8.3.0+9619+9eeb6ed6.noarch is filtered out by modular filtering
  - package container-selinux-2:2.155.0-1.module+el8.3.1+9659+c1901784.noarch is filtered out by modular filtering
  - package container-selinux-2:2.130.0-1.module+el8.3.0+9660+5fcec09e.noarch is filtered out by modular filtering
  - package container-selinux-2:2.124.0-1.gitf958d0c.module+el8.3.0+9668+293abd4d.noarch is filtered out by modular filtering
  - package container-selinux-2:2.130.0-1.module+el8.3.0+9670+b9fad87d.noarch is filtered out by modular filtering
  - package container-selinux-2:2.107-3.el7.noarch is filtered out by modular filtering
  - package container-selinux-2:2.77-5.el7.noarch is filtered out by modular filtering
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

---- I tried everything i could from "checking repo" | "update yum" to "add new repo" | reinstall serveral dependencies but no luck

**Comment by honglinsu** [comment]
Podman is a drop-in replacement for Docker CE. Can you use Podman in Oracle Linux 8: https://docs.oracle.com/en/operating-systems/oracle-linux/podman/

**Comment by totalamateurhour** [comment]
I second what @honglinsu said.  If you also install the `podman-docker` package, this that effectively aliases the `docker` command to `podman`. Installation instructions are here:  https://docs.oracle.com/en/operating-systems/oracle-linux/podman/podman-install.html

**Comment by tvierling** [comment]
As for why Podman was referred to here: Docker CE is not supported on OL8; the OS family that includes Oracle Linux (this includes RHEL and CentOS) has switched to podman as its standard container technology.

I know it's a change, but it's one worth understanding and using if you're going to use this OS family. Give it a try :)

**Comment by Djelibeybi** [comment]
Did you try adding `--nobest` as per the message? That may get you the `container-selinux` package from Docker. If not, you can try adding `module_hotfixes=True` to the Docker CE repo definition to see if that bypasses the modular filtering.

**Comment by johna77** [comment]
> Did you try adding `--nobest` as per the message? That may get you the `container-selinux` package from Docker. If not, you can try adding `module_hotfixes=True` to the Docker CE repo definition to see if that bypasses the modular filtering.

Hey Thanks, So basically i did add `module_hotfixes=True` to Docker-ce.repo to bypass Module but still no luck same package error

For what i understand - It's being filtered out by something with yum, it's being blacklisted/filtered from being installed.

**Comment by johna77** [comment]
@Djelibeybi 

There were blaclisted ( `container-selinux` ) package which not letting docker-ce to install but i did search module filtering from dnf docs - `https://dnf.readthedocs.io/en/latest/command_ref.html#package-filtering` so basically its been filtered out by yum ¯\_(ツ)_/¯.
So for bypass add `module_hotfixes=True` to Docker-ce.repo and then i checked list - 

`dnf module list`
  and then found Container tools - 
`dnf module reset container-tools` - Reset those modules
and then install - `dnf module install container-tools` - (because somehow in OL8 @tvierling "podman as its standard container technology"

It resolves the modular filtering of Container-selinux --- 

"Coffee Break" 

dnf install -y docker-ce --nobest  - ( https://oracle-base.com/articles/linux/docker-install-docker-on-oracle-linux-ol8 follow these steps wonder why " dnf remove -y runc " to remove `buildah` `cockpit-podman` `libvarlink` `podman` i guess same @tvierling   "podman as its standard container technology" ¯\_(ツ)_/¯

at last - `dnf install -y docker-ce --nobest --nogpgcheck`

Worked and installed Docker-ce.

Thanks Everyone.

**Comment by totalamateurhour** [comment]
Thanks for reporting back, @johna77.
