### ISSUE TITLE
Query: Is it possible to upgrade from centos 7 to Oracle Linux 8 with this script ?

### ISSUE THREAD

**Issue by anshu781126** [oracle/centos2ol#82]
Is it possible to upgrade from centos 7 to Oracle Linux 8 with this script ?

If not then I guess I move to centos 7 to Oracle Linux 7 with this script. Then is there a way I can upgrade from OL7 to OL8 ?

**Comment by tvierling** [comment]
We do offer Leapp as an upgrade path from a fully converted OL7 system to get to OL8. See this blog post first, then the first link under "Resources" for documentation:

https://blogs.oracle.com/linux/simplifying-in-place-upgrade-from-oracle-linux-7-to-8-with-leapp

However, there are caveats. Read the documentation very very carefully. Do a full system backup or disk image snapshot BEFORE running Leapp in case of failure.

In particular, if you have installed a lot of software from external repositories, directly with `rpm -i` not from a yum repo, or from EPEL, you may need to do serious cleanup on your system after the upgrade to OL8. Be prepared to look for any leftover `.el7` RPMs after upgrade that need to be updated to EL8/OL8 versions after upgrade.

**Comment by anshu781126** [comment]
thanks for the prompt revert. so in short it is two step process for me to move from centos 7 to OL8.
