### ISSUE TITLE
CentOS 8.3 to Oracle Linux java-1.8.0-openjdk does not keep alternatives config

### ISSUE THREAD

**Issue by richardjohnjensen** [oracle/centos2ol#9]
Noticed that java linking is lost after the distro-sync and reinstall of openjdk

alternatives --list ... have lost all of the java and jre configs
A manually dnf reinstall does not re-deploy the configurations.
A full dnf remove, dnf install restores the alternatives configuration

**Comment by Djelibeybi** [comment]
Thanks for the report. To be honest, I hadn't even considered `alternatives` because a `dnf reinstall` should recreate those links. We'll reproduce this during the week it so we can work out why that's not happening.

**Comment by michalgutowski** [comment]
I just reproduced it on my centos8u3 lab and it seems like we are hitting bug [1200302](https://bugzilla.redhat.com/show_bug.cgi?id=1200302).

**Comment by Djelibeybi** [comment]
Good catch, thanks @michalgutowski.

**Comment by mark-au** [comment]
I do like the idea of comparing the alternatives prior and post update but there could be complexity when (non java) RPMs are updated during the switch and paths intentionally change. This may never happen but we'd have to test with items like pip3 which links to a php3.6 binary, it may have been different in OL8 GA

**Comment by Djelibeybi** [comment]
Strictly speaking, this is a packaging bug and isn't a switch bug. I'm more inclined to close this because of https://bugzilla.redhat.com/show_bug.cgi?id=1200302 and be prepared to open a new issue if we get any more issues with other packages.

**Comment by richardjohnjensen** [comment]
Agreed. I plan to experiment with making a copy of /etc/alternatives directory before the conversion and seeing if I an just replace for my use. The complexity of `alternatives --list` and `alternatives --install` is too complex
